### ISSUE TITLE
Is this a thing?

### ISSUE THREAD

**Issue by chadbr** [handsontable/angular-handsontable#1]
@jansiegel 
Are we going to see an Angular wrapper?

Would love to use HT, but we've moving everything to A2/4/whatever comes next.

Thanks - Chad

**Comment by bukialabi** [comment]
Lol. I love that the only issue is literally called, "Is this a thing?"

**Comment by AMBudnik** [comment]
Hi guys :)

Yup, I agree that we are going a little bit too slow with the development but do not worry, the day will come. 

To be more precise @jansiegel has been scheduled with this task for the end of May - beginning of June. There's one big task that needs his attention before the wrapper. So I guess that in June you'll be able to get new, fresh commits.

Sorry for keeping you waiting. I hope that the wrapper will meet your goals.

**Comment by saurabhajmera** [comment]
@AMBudnik Do you have an approximate date in June for when this will be released?

**Comment by dehim** [comment]
@AMBudnik 
we've been waiting for such a long time，please call developers back to worksite，we are expecting it to be released.

**Comment by AMBudnik** [comment]
Hi @dehim 

the Angular2 wrapper is a work in progress right now. You can check it by the first commit at https://github.com/handsontable/angular2-handsontable/tree/feature/issue-2
Most of the code is this on the local repository but we'd be able to push new commits as soon as the code will get reviewed.

**Comment by paivaric** [comment]
+1

**Comment by swistach** [comment]
I think we can close this issue. I invite you to continue this topic in #2.
If you have ideas, what should be in the wrapper, feel free to share it with us in #2.
