### ISSUE TITLE
"Remote data" example doesn't work 

### ISSUE THREAD

**Issue by madoar** [handsontable/angular-handsontable#10]
The remote data example, located at https://handsontable.github.io/angular-handsontable/examples/remote-data doesn't seem to work:
![peek 2017-09-07 11-52](https://user-images.githubusercontent.com/18488086/30157684-37804f72-93c3-11e7-8773-631214498b7a.gif)

**Comment by swistach** [comment]
Hi @madoar. Now should be ok.
Unfortunately `odata` doesn't support `https://`.

**Comment by madoar** [comment]
It still doesn't seem to work. My developers console contains the following content:
![grafik](https://user-images.githubusercontent.com/18488086/30207532-289db314-9490-11e7-8d87-2b43c2bfbbb3.png)

**Comment by swistach** [comment]
I hope is only cache issue. Could you remove cache for `https://handsontable.github.io/angular-handsontable` site?

**Comment by madoar** [comment]
I've tried to use CTRL + F5 to clear the cache for both https://handsontable.github.io/angular-handsontable/examples/remote-data and https://handsontable.github.io/angular-handsontable/ but it doesn't seem to help.

**Comment by eitland** [comment]
@madoar I'd guess a problem on your end - I just verified on FF, Edge, IE and Chrome and they all work (IE was really slow, especially the first time though but that might have been a network hiccup.)

(This was on Windows.)

**Comment by madoar** [comment]
You're right. I've just tested it with Chrome, where it's working. I'll test it again with Firefox on my next restart.

**Comment by swistach** [comment]
I'll add `--env=production` or something like that into `deploy` npm script. That should helps (hash in a filename).
