### ISSUE TITLE
can't get Handsontable function

### ISSUE THREAD

**Issue by zengwe** [handsontable/angular-handsontable#100]
I want to write a private Editor by Developer guide;
ps: 
```typescrpt
var PasswordEditor = Handsontable.editors.TextEditor.prototype.extend(); 
```
but I can't get 'Handsontable' this function or constructor;

**Comment by AMBudnik** [comment]
Hi @zengwe 

this demo should work https://stackblitz.com/edit/angular-krtyfw?file=src/app/hello.component.ts

**Comment by swistach** [comment]
I think the problem is in our definition file.
To-do in [handsontable/handsontable](/handsontable/handsontable)

**Comment by swistach** [comment]
`extend()` is only as a solution for legacy code.
If you are using TS or ES6+, you should extend predefined editors like in the @AMBudnik's demo.
