### ISSUE TITLE
Angular 6 Handsontable events appear to not be firing

### ISSUE THREAD

**Issue by Djaw** [handsontable/angular-handsontable#104]
### Description

I'm fairly new to angular and handsontable. I'm hoping it's just something trivial and it being an error in the way I'm using the wrapper. I had a working version of handsontable with angular 5 and the previous versions of handsontable and wrapper. 
### Steps to reproduce

1. Start with new angular 6 application. Install latest handsontable version and wrapper.
2. Import handsontable and wrapper into app module and use <hot-table> app html template .
3. Bind <hot-table> (afterChange) event to onAfterChange($event)

### Demo

https://stackblitz.com/edit/angular-gitter-9avxk7

### Your environment
* Angular version:6.0.2
* Handsontable version:4.0.0
* Wrapper version:2.0.0
* Browser Name and version:Chrome 67.0.3396.87
* Operating System:Windows 10

**Comment by swistach** [comment]
Hi @Djaw,
our hooks are now binding as inputs. I described it here: https://github.com/handsontable/angular-handsontable/releases/tag/2.0.0

Modified demo: https://stackblitz.com/edit/angular-gitter-hxmexk?file=app/app.component.ts
