### ISSUE TITLE
how can merge cell by Function

### ISSUE THREAD

**Issue by zengwe** [handsontable/angular-handsontable#105]
example:
_this.hot_ is a Handsontable instance, but _this.hot.MergeCells_ is undefined,so I can't merge cell by official demo；
help me，please！！！
oh， my English is so bad!

**Comment by AMBudnik** [comment]
Hi @zengwe 

you have to use `getPlugin` method to get to the plugin's methods.
Here is an example http://jsfiddle.net/m3uyLj7f/

**Comment by zengwe** [comment]
@AMBudnik Getted it, thanks

**Comment by swistach** [comment]
In Handsontable v5.0.0+, `getPlugin('mergeCells')` should return properly `MergeCells` interface.
