### ISSUE TITLE
how to add comment column to the table 

### ISSUE THREAD

**Issue by jnjagtap** [handsontable/angular-handsontable#106]
how to add comment column to table a and  previous comments should remain unchanged .in angularjs
using handsontable

**Comment by AMBudnik** [comment]
Hi @jnjagtap 

Can you share a draft? I am not sure what you would like to achieve. And just to confirm - are you using the AngularJS, not Angular 2+?

**Comment by jnjagtap** [comment]
yes i  am using angularjs.
![screenshot from 2018-07-02 15-11-29](https://user-images.githubusercontent.com/40597317/42158240-8c99c3fa-7e0d-11e8-9bda-9a15417c2030.png)


in this at last there should be colunn comment and whenver data updated but comment should e remained as it is and we can npw addd more shoes

**Comment by jnjagtap** [comment]
I could able to create tables using nghandsontable syntax. But I want to add some comment to  table . So that while opening table definition from catalog, the same comment should be present.

**Comment by AMBudnik** [comment]
Hi @jnjagtap 

Comments are an array of objects provided via[ `cell` property](https://docs.handsontable.com/pro/4.0.0/demo-comments_.html)

```js
cell: [
    {row: 1, col: 1, comment: {value: 'Some comment'}},
    {row: 2, col: 2, comment: {value: 'More comments'}}
  ]
```

you can add comment to each cell, you just need to define then in the array. If user adds a comment manually you should also push it to the array of comments for further use. Without it the comment will be lost after you load the data again.

**Comment by AMBudnik** [comment]
We do not have any option like `comment column`, If you think of a column that is editable and you want the user to post there anything and then remain the data after you load yours from the database you need to pass this data to the server via `afterChange` hook.

Sorry if I do not get the idea.

**Comment by swistach** [comment]
Issue moved to [handsontable/ngHandsontable #243](https://github.com/handsontable/ngHandsontable/issues/243) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kbhuvana** [comment]
I believe there are many more pleasurable opportunities ahead for individuals that looked at your site.
<a href="http://www.zerobugacademy.com/angularjs-training-in-chennai">|Angularjs training in velachery,Chennai</a>

**Comment by bhuvizerobug** [comment]
You truly did more than visitors’ expectations. Thank you for rendering
these helpful, trusted, edifying and also cool thoughts on the topic to
Kate.
Visit Us: http://www.zerobugacademy.com/angularjs-training-in-chennai
