### ISSUE TITLE
how can I render only one header 

### ISSUE THREAD

**Issue by zengwe** [handsontable/angular-handsontable#108]
`        let rowResizeIntance = this.getManualRowResizeInstance();
        for(let i = 0; i < selectArea.from.row - selectArea.to.row + 1; i++) {
            rowResizeIntance.setManualSize(i + selectArea.from.row, height);
            for(let j = 0; j < this.cellDatas[i + selectArea.from.row].length; j++) {
                this.cellRender(i + selectArea.from.row, j);
            }
            //currHeightArr[i + selectArea.from.row] = height;
        } `
I set a row height,and render this row,but can't render this row header!
please help me!
thanks!

**Comment by AMBudnik** [comment]
Hi @zengwe 

Can you tell me what is the scenario? Ar you using a one-level header for many columns or nestedHeaders?

**Comment by zengwe** [comment]
I set a row'height,and I render all cells of the row,but header is not change of the row. now, I just render the whole of table。

**Comment by AMBudnik** [comment]
If you would like to change a header height you need to use the [`columnHeaderHeight `](https://docs.handsontable.com/pro/5.0.0/Options.html#columnHeaderHeight)option.

**Comment by swistach** [comment]
I don't see any activity for the last two weeks.
@zengwe: I hope, you've resolved your problem. Feel free to reopen this issue if not.
