### ISSUE TITLE
Incorrect hook name: afterBeginEditing

### ISSUE THREAD

**Issue by swistach** [handsontable/angular-handsontable#109]
In `hot-table.component.ts` is a typo in `afterBeginEditing` hook name.
By the way, we should check the others `@Input` to be sure that they are correct.

https://github.com/handsontable/angular-handsontable/blob/master/lib/ce/src/hot-table.component.ts#L145

**Comment by AMBudnik** [comment]
_[inform Gr# 16239]_

**Comment by arfis** [comment]
Hi there. When will there be a new version of handsontable with this bug fixed?

**Comment by AMBudnik** [comment]
Hi @arfis 

there's only a code review missing. We should be able to get this done in the next release 12th Sep

**Comment by arfis** [comment]
Ok and are you sure about the 12th?

**Comment by AMBudnik** [comment]
Thank you for reminding about this issue @renatuzz 
I have forwarded it to our CTO

**Comment by caseahr** [comment]
Is there a workaround?  Referring to the mis-named 'afterBeginEdting' (missing the "i") does not seem to fire the event.

**Comment by AMBudnik** [comment]
The topic has been already fixed and reviewed. Soon we'll provide an official fix (not a workaround).

**Comment by swistach** [comment]
Released in 3.0.0
