### ISSUE TITLE
Doc - Conflict with zone.js should be more precise

### ISSUE THREAD

**Issue by mselerin** [handsontable/angular-handsontable#11]
### Description
In the quick-start page (https://handsontable.github.io/angular-handsontable/quick-start), step 3 `Import Handsontable before Zone.js` should be more precise about the import order of the libraries.

My project does not use the angular-cli (but is built with webpack).
I have adapted my polyfills.ts as specified in step 3 but still have the famous "ZoneAwarePromise" problem.

The error still occurs because of the import order of the differents libraries. My main module (AppModule) was imported *after* zone.js. This module contains the import for "angular-handsontable" which import "handsontable".

### Solution
The solution was to remove "zone.js" from polyfills.ts and to import it right after importing my AppModule.

My final code in main.ts looks like this :
```typescript
// Main App module
import {AppModule} from './app.module';


// Polyfills
import './polyfills';
import 'zone.js/dist/zone.js';


// Bootstrap Angular
import {enableProdMode} from "@angular/core";
import {platformBrowserDynamic} from "@angular/platform-browser-dynamic";

if (production)
    enableProdMode();

platformBrowserDynamic().bootstrapModule(AppModule);
```

### More details
The webpack configuration inside angular-cli (also in my config) bundle the whole 'polyfills.ts' file in a separate file. As zone.js is imported inside this file, it is still loaded *before* the main code and, therefore, before handsontable.

The solution proposed in the current document will bundle 'handsontable' inside the polyfills. While it is working, following the principle of polyfills (giving a browser methods it has not yet implemented), I think we should not import handsontable inside this file.

Also, explaining this problem in the documentation seems like a nice idea, isn't it ? ;-)

My 2 cents...

**Comment by swistach** [comment]
Hi @mselerin,
Thank you for your investigation.
We have to check why ZoneAwarePromise think that it is overwritten.
Step 3 in `Quick start` is a temporary workaround (I would like to remove this step in the stable version).
Are you using a ts-loader/js?

**Comment by mselerin** [comment]
Hi,

I am using the @ngtools/webpack loader provided by Angular (just like the angular-cli).
Also, a small hint : when I enable "aot", the error is back ;-(

Ang btw, the ZoneAwarePromise just check if window.Promise is modified or not. I'll try to help and to figure out where the Promise function is overwritten...

**Comment by swistach** [comment]
Ok, we have to check it. 
Thanks! I suppose, that could be related to `handsontable.js`.

**Comment by mselerin** [comment]
I just had a look on the code and see nothing wrong inside Handsontable.

I see that Babel is used to build the distribuable version. I think that Babel include some sort of polyfills and could create their own version of Promise.

I am not a Babel expert so I can't be sure...

**Comment by Pradhyo** [comment]
I was using a blank project created using angular cli.
The only change I had to make in the Quick start was in step 3 - `import 'angular-handsontable';` instead of `import 'handsontable';`
```
import 'angular-handsontable';

/*********************************************************
* Zone JS is required by Angular itself.
*/
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

**Comment by swistach** [comment]
@mselerin Exactly, I thought about `es6-promise` :)

@Pradhyo since `zone.js@0.8.19`, this workaround isn't necessary anymore.
