### ISSUE TITLE
Handsontable not working in angular elements

### ISSUE THREAD

**Issue by kaosdev** [handsontable/angular-handsontable#110]
I have just imported the HotTableModule in an angular elements app, compiled it, and then used it inside another angular app.

I have removed zone js from the angular elements app to remove conflicts, but when the main app start I get.

Uncaught Error: Zone already loaded

Removing the import also remove the error and the app load correctly.

**Comment by swistach** [comment]
Hi @kaosdev,
Could you add more details about versions of the wrapper, Handsontable and Angular?

Also, it will be helpful, if you could prepare an example on stackblitz.

**Comment by kaosdev** [comment]
I created an example project and published on github.
Check the repo https://github.com/kaosdev/angular-elements-microapp1

**Comment by kaosdev** [comment]
handsontable version: 2.0.0
angular version: 6.0.8

What do you mean with version of the wrapper?

**Comment by wojciechczerniak** [comment]
>  What do you mean with version of the wrapper?

`@handsontable/angular` is the Angular wrapper package for `handsontable`. Both are needed to use the Handsontable inside Angular app.

https://www.npmjs.com/package/handsontable
https://www.npmjs.com/package/@handsontable/angular

**Comment by kaosdev** [comment]
Sorry for the late reply.

`@handsontable/angular` version: 2.0.0
`@handsontable` version: 5.0.0

**Comment by AMBudnik** [comment]
Hey @kaosdev 

sorry for bringing up the old cases but have you managed to create use the project without further obstacles? I was checking the topic and this one seems to be unsolved but since August we did a lot of new updates so I decided to ask first.

**Comment by kaosdev** [comment]
Hi, thanks for contacting me.
I have taken other routes since we last spoke,
So I really don't know if this issue was fixed with other updates.

**Comment by AMBudnik** [comment]
Thank you for the fast reply.

I guess that I can close the topic and open it up if someone brings some updates.
