### ISSUE TITLE
Incorrect afterChange callback arguments

### ISSUE THREAD

**Issue by smitpsanghavi** [handsontable/angular-handsontable#111]
### Description
When I create a HOT instance I get wrong arguments in the afterChange callback.
I expect the arguments to be of type `changes: Array<[number, string | number, any, any]>, source: any`
But, what I get is `_Handsontable.Core, changes: Array<[number, string | number, any, any]>`

This issue came up after I started using *ngIf to create HOT. Previously, I used [hidden] tag to show hide the HOT. But, due to some requirements I had to change it to *ngIf.

I traced the call stack in Chrome to be like this:
```
onHandsontableAfterChange (work-order-form.component.ts:822)
afterChange (work-order-form.component.ts:731)
component._ngZone.run (handsontable-angular.js:108)
push.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
onInvoke (core.js:4371)
push.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
push.../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
run (core.js:4261)
mergedSettings.(anonymous function) (handsontable-angular.js:107)
run (handsontable.js:5306)
Core.runHooks (handsontable.js:14322)
applyChanges (handsontable.js:11777)
(anonymous) (handsontable.js:11893)
resolve (handsontable.js:11711)
checkIfQueueIsEmpty (handsontable.js:11628)
removeValidatorFormQueue (handsontable.js:11622)
(anonymous) (handsontable.js:11692)
done (handsontable.js:11814)
(anonymous) (handsontable.js:11835)
rateValidator (work-order-form.component.ts:1038)
validator (work-order-form.component.ts:689)
(anonymous) (handsontable.js:11831)
push.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
push.../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
push.../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
ZoneTask.invoke (zone.js:485)
timer (zone.js:2054)
setTimeout (async)
scheduleTask (zone.js:2075)
push.../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask (zone.js:407)
push.../node_modules/zone.js/dist/zone.js.Zone.scheduleTask (zone.js:232)
push.../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask (zone.js:255)
scheduleMacroTaskWithCurrentZone (zone.js:1114)
(anonymous) (zone.js:2090)
proto.(anonymous function) (zone.js:1394)
Core.validateCell (handsontable.js:11830)
validateChanges (handsontable.js:11680)
Core.setDataAtCell (handsontable.js:11892)
populateFromArray (handsontable.js:11557)
Core.populateFromArray (handsontable.js:12027)
BaseEditor.saveValue (handsontable.js:7888)
BaseEditor.finishEditing (handsontable.js:7963)
EditorManager.closeEditor (handsontable.js:35491)
EditorManager.closeEditorAndSaveChanges (handsontable.js:35505)
onKeyDown (handsontable.js:35271)
run (handsontable.js:5306)
Core.runHooks (handsontable.js:14322)
(anonymous) (handsontable.js:35336)
callbackProxy (handsontable.js:2213)
push.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
push.../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
push.../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
invokeTask (zone.js:1540)
globalZoneAwareCallback (zone.js:1577)
```

HOT Settings:
```javascript
afterChange: (changes: Array<[number, string | number, any, any]>, source: string) => { this.onHandsontableAfterChange(changes, source); },
```

HOT HTML:
```html
<div class="ui-g-12" *ngIf="isTableDataReady">
    <div class="ui-g-12" style="overflow:hidden; height:400px">
        <hot-table [settings]="settingsObj" [hotId]="hotInstanceId"></hot-table>
    </div>
</div>
```

### Steps to reproduce
1. Create a HOT with *ngIf condition to be false.
2. Create the data
3. Make *ngIf condition to be true
4. Make a change in the table and check the arguments received by the afterChange callback

### Your environment
* Angular version: 6.0.9
* Handsontable version: 5.0.0
* Wrapper version: 2.0.0
* Browser Name and version: Chrome 67.0.3396.99 OR Firefox 61.0
* Operating System: Windows 10 Version 1803

**Comment by minchopm** [comment]
Same behavior for beforeOnCellMouseOver, and afterInit but in my case I am loading the grids inside router outlet

**Comment by swistach** [comment]
Hi @smitpsanghavi, @minchopm,
I've mentioned about this change in our release notes: https://github.com/handsontable/angular-handsontable/releases/tag/2.0.0

The first argument of hooks' callback is a reference to Handsontable.
You can use `hooks` in the following ways:
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `<hot-table [afterChange]="onAfterChange"></hot-table>`
})
export class AppComponent  {
  onAfterChange = (hotInstance, changes, source) => {
    // code
  };
}
```
or
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `<hot-table [settings]="settings"></hot-table>`
})
export class AppComponent  {
  settings = {
    afterChange: (hotInstance, changes, source) => {
      // code
    }
  }
}
```

**Comment by Abhith** [comment]
There is a type error if we try to use like
```ts
 settings = {
    afterChange: (hotInstance, changes, source) => {
      // code
    }
```
Because **instance** not mentioned [here](https://github.com/handsontable/handsontable/blob/c2ba2dc02e3eb883a58f976ef5944fa629dc981d/handsontable.d.ts#L1549)

**Comment by cgalvezv** [comment]
Any solution for that?

**Comment by AMBudnik** [comment]
@cgalvezv the explanation of @swistach doesn't work for you?

**Comment by cgalvezv** [comment]
@AMBudnik now really, [handsontable.d.ts](https://github.com/handsontable/handsontable/blob/c2ba2dc02e3eb883a58f976ef5944fa629dc981d/handsontable.d.ts#L1549) (don't exist's the **Core** instance in the **hooks** interfaces) generate problem to build my project. I had to downgrade the `@handsontable\angular` package  (from 2.0.0 to 1.0.0-beta5) to be able the compile without problem, but I think this is not a good solution, some help or someone who has solved this in another way?

**Comment by daleclements** [comment]
This is a pretty big problem for several reasons

```
settings = {
    afterChange: (hotInstance, changes, source) => {
      // code
    }
}
```

can work, but only because you aren't specifying the type for the settings object (which removes the main benefit of using TypeScript in the first place). In all of the official documentation, the settings object is typed as a GridSettings object ([example](https://handsontable.com/docs/7.0.0/frameworks-wrapper-for-angular-custom-editor-example.html)) which is something you should be able to do. With the modified hook signatures, it won't compile.

If a developer is trying to use a hook, the only way to know what parameters the hook takes is

1. Look at the Handsontable documentation
2. Look at the GridSettings object

and the addition of the hot instance to the method signature makes both of those options fail. The only way for a developer to know what parameters to use for hooks is to find this Github issue or comb through the release notes, because this massive deviation from the official Handsontable documentation isn't part of the angular-handsontable documentation.
