### ISSUE TITLE
Multiple lazy loaded modules can not use handsontable module.

### ISSUE THREAD

**Issue by harish-suthar** [handsontable/angular-handsontable#114]
### Description
I have multiple child modules which are lazy loaded in app module and from those multiple child modules two are using handsontable module, but when using ng serve --prod it gives error as below:

"main.855e35e52f82410ee929.js:180 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (main.855e35e52f82410ee929.js:180)
    at n (main.855e35e52f82410ee929.js:180)
    at Object.<anonymous> (main.855e35e52f82410ee929.js:180)
    at n (main.855e35e52f82410ee929.js:180)
    at Object.<anonymous> (main.855e35e52f82410ee929.js:180)
    at n (main.855e35e52f82410ee929.js:180)
    at main.855e35e52f82410ee929.js:180
    at main.855e35e52f82410ee929.js:180
    at Object.kf/3 (main.855e35e52f82410ee929.js:180)
    at f (runtime.9d0bd1286ab6945d9cf9.js:1)"

### Steps to reproduce

1. Add HotTableModule.forRoot() in app module
2. Add HotTableModule in child module but it should provide method like HotTableModule.forChild() which is missing and causing error.
3. Now run the app using ng serve --prod

### Your environment
* Angular version: 6.1
* Handsontable version: 2.0.0

**Comment by AMBudnik** [comment]
Hi @harish-suthar 

can you create a [Stackblitz demo](https://stackblitz.com/edit/angular-p2bxbs?file=src%2Fapp%2Fapp.component.ts)? It'll be easier to understand what's going on in the example.

**Comment by harish-suthar** [comment]
@AMBudnik please check the stackblitz demo for the same on link below:

https://stackblitz.com/edit/angular-handsontable-lazy-load-issue

**Comment by AMBudnik** [comment]
Hi @harish-suthar 

is that a correct demo? I get `404` no matter what I click and a ton of errors in the console besides the one you've mentioned.

![image](https://user-images.githubusercontent.com/10757813/44570479-4e872e00-a77e-11e8-979c-96e6933e0417.png)

**Comment by harish-suthar** [comment]
@AMBudnik Yes that's a correct one, its just that to show that all modules except those who have imported handsontable module are working perfect i have created one error module with not-found component, and the app by defaults loads this page only, thus you are able to see this 404 message, but you can see if app is loaded first time then console will not have any errors, this errors occurs only when you visit manager or employee routes either via url or via clicking the links provided.

Kindly check again then you will see the errors on exact places.

**Comment by AMBudnik** [comment]
Hi @harish-suthar 

I have just got a reply from our Angular developer and he told me that the issues you're getting relate to the lack of lazy loading functionality. We do not support it yet.

**Comment by harish-suthar** [comment]
@AMBudnik if this issue is due to lack of lazy loading functionality i guess it must be closed only after that is done, isn;t it ?

**Comment by AMBudnik** [comment]
It is more a feature request for the vanilla version than the wrapper. We have the following features already reported at the `infinite scroll` feature request at https://github.com/handsontable/handsontable/issues/607

The issue gets opened as soon as any of the developers make the first commit on it.

**Comment by harish-suthar** [comment]
@AMBudnik thanks for the information.

**Comment by AMBudnik** [comment]
You're welcome @harish-suthar 
if we're missing anything on that subject please leave a comment.

**Comment by harish-suthar** [comment]
Hello @voznik 

Thanks for checking it, but the issue is not what you are explaining and even I tried your solution too, and that's not working, I don't know why?


However, I tried to fix this issue by creating my own shared module and a component that uses handsontable and then I used that in my components and its working like a charm.

I hope this solution will work for you and all those who came on this thread for the same issue.

@AMBudnikI hope you can also address people on this thread for a solution if this one is a good fit from your team's view.

Visit the working demo link here = [https://stackblitz.com/edit/angular-handsontable-lazy-load-issue-fixed](https://stackblitz.com/edit/angular-handsontable-lazy-load-issue-fixed)

Regards,
Harish Suthar
