### ISSUE TITLE
Some Documentation would be extremely helpfull

### ISSUE THREAD

**Issue by sittingbool** [handsontable/angular-handsontable#115]
### Description
Cannot find how to use it in code.

### Steps to reproduce
1. install via npm
2. add module and hot-table-tag
3. see an empty table

### Your environment
* Angular version: 6
* Handsontable version: 5.01
* Wrapper version: 2.00
* Browser Name and version: Chrome
* Operating System: OSX latest

**Comment by sittingbool** [comment]
Want to know so far: 
- how to configure my table (angular says no input for [options]="{...}")
- how to add custom formatters

(all in Angular)

**Comment by sittingbool** [comment]
I saw all the examples but those cover hardly the features handsontable has to offer.
I want to do many things.
But for starters I wanted to add formatters. 
I also was trying the inofficial wrapper ng-handsontable. there I had options that I could set. Like formatting my columns to show percent.
Now I need a column for example that can handle currency as well as percent.

**Comment by sittingbool** [comment]
okay, I now found the code, finally... Its in the lib directory instead of src. I will try to figure out what to do from there. But documentation what the components have to offer would be helpfull. or at least link the ts file to the components so one can have a look without searching a whole hour.

**Comment by AMBudnik** [comment]
Most of our demos are made in Vanilla in the documentation. However, we are working on a new documentation where you'll be able to switch between Vanilla, Angular, React and Vue to check how to handle certain situations in you chosen framework.

Please check the following tutorial for numeric cell type https://docs.handsontable.com/pro/5.0.1/demo-numeric.html. It shows how to use `numericFormat` to add currencies and define decimal places. We do not have demos for all the cases but if there's something missing please let me know. I'll do my best to help. (We are also planning to share the examples on our blog and in the `how to` section but it's a plan for Q4).

But getting back to the example of percentage and currency column here's a demo that I've just made https://stackblitz.com/edit/angular-dkxbw2?file=src/app/hello.component.ts
The syntax inside the `settings` object is the same for Angular and Vanilla.

ps. If any example is more complicated or you do not want to share it on public I higly encourage to write me at support@handsontable.com

**Comment by ashishyadav0019** [comment]
Hie,
For initial starting please find a demo [table](https://stackblitz.com/edit/angular-handsontable-demo1).

**Comment by swistach** [comment]
Hi @sittingbool,
In #126 is a list of our planned examples which we would add to the documentation - you can add there your suggestions. In the meantime, you can use https://handsontable.com/docs/6.2.0/frameworks-wrapper-for-angular-examples.html or https://handsontable.github.io/angular-handsontable/

Thank you @ashishyadav0019 for your help 👍
