### ISSUE TITLE
Need Demo for Angular 6

### ISSUE THREAD

**Issue by ytnydv** [handsontable/angular-handsontable#118]
### Description
When ever i try to use handsontable-pro 

### Steps to reproduce
Am just following instructions provided here,
https://github.com/handsontable/angular-handsontable

### Demo
NO link

### Your environment
* Angular version: 6.0.1
* Handsontable version: 2.0.0
* Wrapper version:5.0.2
* Browser Name and version: chrome 69
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hi @ytnydv 

here's a demo with Angular 6 and Handsontable-pro https://stackblitz.com/edit/angular-f9g1ib?file=src/app/hello.component.ts

Do you need any specific settings applied?
