### ISSUE TITLE
Setting dropdown value from http response

### ISSUE THREAD

**Issue by abhishekb91** [handsontable/angular-handsontable#119]
### Description

I need to populate a dropdown field in my sheet. If I use a local array and pass it as a `source` to the dropdown field, it works fine. However, if I update array used in `source` field, after getting a response from my http, it doesn't render anything.

Is this the way I should be doing this, or am I doing it wrong?

### Steps to reproduce

1. Create a dropdown field 
2. use a blank array for as a source for it
3. Update the source array after getting the response from a service
4. Check the dropdown field in the sheet

### Demo

https://stackblitz.com/edit/handsontable-angular-ufbxmx

### Your environment
* Angular version: 6.1.2
* Handsontable version: ^5.0.2
* Wrapper version: ^2.0.0
* Browser Name and version: Google Chrome, v 69.0.3497.100
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @abhishekb91 

you can pass the `source` for the dropdown cell type via variable, here is an example https://stackblitz.com/edit/angular-sz5bve?file=src/app/hello.component.ts
Each time you get a response from the server you just replace the `mysource`

**Comment by abhishekb91** [comment]
Hi @AMBudnik ,

I tried the following thing, but I'm still can can't update the dropdown field value. Following is as example of what I changed.

https://stackblitz.com/edit/handsontable-angular-nf6hlq

If possible, can you explain me what changes do I need to make in my demo to make it work, Thanks

**Comment by AMBudnik** [comment]
I've checked that but haven't found an answer so I've asked a colleague for help. As soon as I get the code I'l be back.

**Comment by abhishekb91** [comment]
Hi @AMBudnik,

I really appreciate you taking time out and answering my question. I've tweaked your solution a bit, as my intentions to have a delay was to mimic the http response. Please take a look at https://stackblitz.com/edit/handsontable-angular-yxcuvl

**Comment by AMBudnik** [comment]
Great. Does it mean that now it fully meets the requirements?

**Comment by abhishekb91** [comment]
oh yeah, it does thanks :)

**Comment by AMBudnik** [comment]
Great! Thank you for confirmation.
