### ISSUE TITLE
Use more specific types than object, any or any[]

### ISSUE THREAD

**Issue by madoar** [handsontable/angular-handsontable#12]
Currently, all components of `angular-handsontable` make heavy use of `object`, `any` and `any[]`.
I believe it would be better for the developers to use more specific types than the ones above.

Whenever I'm unsure what fields an object of type `any` should contain I normally take a look at the interface definition (in case it is provided), this helps quite a lot.
This would be especially nice, because you also provide a `d.ts` file at https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts.

**Comment by swistach** [comment]
Unfortunately, handsontable.d.ts is imperfect. Firstly we have to improve this file and the next step should be use patched definition file in this wrapper.
This issue is probably related to #7

**Comment by swistach** [comment]
I think we can close this issue.
