### ISSUE TITLE
Conditional formatting and External search example for Angular 6

### ISSUE THREAD

**Issue by Kalpb** [handsontable/angular-handsontable#121]
Hi,

I want to know how to use conditional formatting and external search using angular 6.
For external search, I mean having a input and a button outside the table and click on button it should search for that value in the table. 

Your environment
* Angular version: 6
* Handsontable version: 6.0.1
* Wrapper version: @handsontable/angular: 2.0.0
* Browser Name and version: any
* Operating System: any

Thanks in Advance

**Comment by AMBudnik** [comment]
Hi @Kalpb 

Here is our conditional formatting demo in Angular app https://stackblitz.com/edit/angular-cq1nwz?file=src/app/hello.component.ts

**Comment by AMBudnik** [comment]
And here https://stackblitz.com/edit/angular-laxwog?file=src/styles.css is a search example

**Comment by Kalpb** [comment]
@AMBudnik : Thank You...  Worked like charm :)
