### ISSUE TITLE
Angular Event Bindings broken with Angular 6 with handsontable\angular 2.0

### ISSUE THREAD

**Issue by Calidus** [handsontable/angular-handsontable#122]
### Description
Binding hooks with () in the HTML template do not fire with Angular 6 with handsontable\angular 2.0. They previously worked fine with Angular 5 and handsontable\angular 1.0 .

Does not work anymore
`<hot-table data="values" (afterChange) ="afterChange($event)"> <hot-table>`

vs 

Works
```
<hot-table [settings]="settings"><hot-table>

this.settings = {
   data: this.values,
   afterChange: (changes) => this.afterChange(changes)
}
```

### Steps to reproduce

1. Use event binding
2. Trigger a hook

### Demo

https://stackblitz.com/edit/angular-bewcmg

### Your environment
* Angular version: 6.1
* Handsontable version: 4.0
* Wrapper version: 2.0
* Browser Name and version: Chrome 69
* Operating System: Win 10 64biy

**Comment by Calidus** [comment]
Update: Event binding works with Angular 6 and  @handsontable/angular version 1.0.0-beta5

**Comment by AMBudnik** [comment]
Hi @Calidus 

I believe that this is the same issue as reported at https://github.com/handsontable/angular-handsontable/issues/123.
Can you confirm?

**Comment by Calidus** [comment]
They are slightly different, the event is not getting triggered if you use the parentheses to do event binding in the template. In #123 if you use a settings object the event is trigger but it doesn't return the values specified in the documentation.

**Comment by wojciechczerniak** [comment]
Hi,

Please check the release notes for 2.0.0 [1]. There was a very important change in this matter:

> We've refactored @Outputs to @Inputs. Now you can use return false in callbacks. 

[1] https://github.com/handsontable/angular-handsontable/releases/tag/2.0.0

**Comment by Calidus** [comment]
Could the information from the release notes be added to the official docs? Either in the angular wrapper section or the events section?

https://handsontable.com/docs/6.0.1/frameworks-wrapper-for-angular-installation.html
https://handsontable.com/docs/6.0.1/Hooks.html#event:afterChange

**Comment by wojciechczerniak** [comment]
Yeah, you're right. Angular section is falling behind when it comes to examples. 

I've created an issue for that: #126
