### ISSUE TITLE
afterChange hook not passing the correct parameters to call back with Angular 6

### ISSUE THREAD

**Issue by Calidus** [handsontable/angular-handsontable#123]
### Description

After Change should be passing changes(a multidimensional array) and source to a call back function according to the docs.
https://docs.handsontable.com/pro/6.0.1/Hooks.html#event:afterChange
### Steps to reproduce

1. Make a Change in a cell expect changes array to have atleast 1 element in it
2. Changes isn't even an array in Angular 6 anymore as length is undefined, 

![image](https://user-images.githubusercontent.com/1683712/46824235-36836200-cd5e-11e8-8524-d62ec4564ef9.png)

### Demo

Angular 5 Working: https://stackblitz.com/edit/handsontable-angular-ga3ib9?file=.angular-cli.json
Angular 6 Not Working https://stackblitz.com/edit/angular-u1boq6?file=src/app/hello.component.ts
### Your environment
* Angular version:
* Handsontable version:
* Wrapper version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
Hello,

Please take a look at release notes for 2.0.0 [1]. Arguments for hooks are slightly different when you use Angular wrapper:

> All of the available hooks have an additional argument at the first position - a reference to an instance of Handsontable.

[1] https://github.com/handsontable/angular-handsontable/releases/tag/2.0.0

**Comment by talamaska** [comment]
@wojciechczerniak correct, but the interfaces exposed by the handsontable npm package are not reflecting this

**Comment by wojciechczerniak** [comment]
You're right. We've found a better way since then and are going to fix this issue with #150

**Comment by swistach** [comment]
Hi @Calidus and @talamaska, thank you for your involvement!
Please try v5.0.0 which is compatible with Handsontable's definition file.
