### ISSUE TITLE
HotSettingsResolver doesn't allow to introduce new settings for custom plugins

### ISSUE THREAD

**Issue by andriychuma** [handsontable/angular-handsontable#124]
### Description
Creating custom external plugin assumes introducing of new settings. In [this example](https://github.com/handsontable/handsontable-skeleton/blob/master/plugins/external/example/helloWorldPlugin.js) a new setting `helloWorldPlugin` was introduced. On the other hand, `mergeSettings` method of the `HotSettingsResolver` class eliminates any non standard setting provided. So that there is no official way to extend settings object in the interests of custom plugin.

### Steps to reproduce

1. Provide settings object with any non standard property, e.g. `settings = { helloWorldPlugin: true }`
` <hot-table [settings]="settings"></hot-table>`
2. After HOT instance got created, retrieve and inspect settings object via `hotInstance.getSettings()`
3. Settings do not contain `helloWorldPlugin` property.
Expected result: `helloWorldPlugin` is still in settings object.

A good fix might be to provide ability to explicitly register new settings via `HotSettingsResolver` API.

### Your environment
* Angular version: 6.1.3
* Handsontable-pro version: 5.0.1
* Wrapper-pro version: 2.0.0
* Browser Name and version: Chrome 69.0.3497.100
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the report.

I will ask our developer to take a look at it.

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting. That is a pretty complicated task for us right now.

However, it sounds like a good plan.

**Comment by andriychuma** [comment]
Sure, thanks. As a workaround I incorporate my plugin's settings into those of an existing (standard) plugin. That way they aren't being automatically removed so that I can fetch them later.

**Comment by swistach** [comment]
Released in 3.0.0

**Comment by AMBudnik** [comment]
Hey @andriychuma 

please update and let us know if it works for you.

**Comment by andriychuma** [comment]
I tested and everything works well. Thank you for the update!

**Comment by AMBudnik** [comment]
Thank you for the confirmation @andriychuma 

I guess that we can close the issue.
