### ISSUE TITLE
Error while creating custom editor

### ISSUE THREAD

**Issue by abhishekb91** [handsontable/angular-handsontable#127]
### Description
I wanted to custom create an editor and was reading the docs how to do it. I found the necessary page which describes a way to extend an editor to create a custom editor (https://handsontable.com/docs/6.0.1/tutorial-cell-editor.html). However, when I implement this I get many errors. Can you guide me how should I proceed with creating a custom dropdown editor?

Please note, I'm not looking to extend a TEXTBOX editor but want to create a custom editor to include a dropdown which will support selecting multiple values.

### Steps to reproduce

1. Create an application
2. Follow the guidelines provided in the docs (https://handsontable.com/docs/6.0.1/tutorial-cell-editor.html)

### Demo

https://stackblitz.com/edit/handsontable-angular-nvwkq9

### Your environment
* Angular version: 6.1.1
* Handsontable version: 5.0.2
* Wrapper version: 2.0.0
* Browser Name and version: Google Chrome 69.0.3497.100
* Operating System: macOS Mojave 10.14

**Comment by AMBudnik** [comment]
Hi @abhishekb91 

here's an example of a custom editor in a Angular app. Hope it helps
https://stackblitz.com/edit/angular-dirbuj?file=src/app/hello.component.ts

**Comment by abhishekb91** [comment]
Can you please provide me with an example of a dropdown in the cell?

**Comment by AMBudnik** [comment]
Do you mean something like this https://stackblitz.com/edit/angular-handsontable-custom-editor-kjwxzd?file=app/app.component.ts?
If not please share more details

**Comment by swistach** [comment]
Hi @abhishekb91,
We'll add an example in our documentation - it is one of the point of the to-do list in #126.

I close this issue but feel free to reopen if you'll have difficulties with creating a custom editor.
