### ISSUE TITLE
Getting Comments Values when Updated/Added

### ISSUE THREAD

**Issue by abhishekb91** [handsontable/angular-handsontable#128]
### Description
I want to save all the added comments to the database, and in order to do that I need to get the comments user adds/edits. We have `afterChange` handler to notify whenever a cell value changes, is there any similar handler to notify whenever the comment value changes.
Right now I'm using `afterSetCellMeta` to get cell comments, however, the issue with using that is it doesn't give me `before`-`after` value, and there's no way for me to determine if the comment was changed or not. Is there a better way currently to deal with comments?

### Demo

https://stackblitz.com/edit/handsontable-angular-jvow49

### Your environment
* Angular version: 6.1.1
* Handsontable version: 5.0.2
* Wrapper version: 2.0.0
* Browser Name and version: Google Chrome 69.0.3497.100
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting @abhishekb91 

Have you made any progress on that subject?

**Comment by abhishekb91** [comment]
Hi @AMBudnik, I'm still using `afterSetCellMeta` to get cell comments. Do you know if there's a better way to do this?

**Comment by AMBudnik** [comment]
Have you tried to create a matrix of comments via [`getCommentAtCell` ](https://handsontable.com/docs/6.1.1/Comments.html#getCommentAtCell)method? You can update it with the `afterSetCellMeta` hook that you already use. It is a little bit more coding but you will be able to get a comment `before` for the same cell.

**Comment by swistach** [comment]
Hi @abhishekb91, you can use `getCommentMeta`: https://stackblitz.com/edit/angular-tdc5pf?file=src%2Fapp%2Fapp.component.ts

Unfortunately, `getCommentAtCell` is missing in our definition file - we will add it soon.

I think we could close this issue - feel free to reopen if you'd like to continue the discussion.
Thank you for your sharing! 👍
