### ISSUE TITLE
New line added when pasting data

### ISSUE THREAD

**Issue by tasinclair1** [handsontable/angular-handsontable#129]
### Description
When pasting in decimal data from a spreadsheet into a handsontable cell set as type 'numeric' , what appears to be a hidden new line character is added into each cell. This then triggers my error validation on the cells as my data is now treated as 'text' rather than 'numeric'.

Each cell can be manually editied to resolve the issue but for large datasets this is time consuming and annoying for my users.

This error occurs on Chrome and Edge but I have been unable to reproduce on Firefox.

### Steps to reproduce
1. Generate some random decimal values in a column in a spreadsheet (7202.33, 887.6, 878.59235 etc...). The error does not seem to occur for 'point zero' values.
2. Copy the data into the table
3. The cells should be highlighted red indicating that they are not valid.
4. Double click on the red cell to edit the value and you will see the new line.

### Demo
https://stackblitz.com/edit/handsontable-angular-seuuhc

### Your environment
* Angular version: 7.0.0 (6.1.0 also affected)
* Handsontable version: 4.0.0
* Wrapper version: 2.0.0 (@angular/handsontable)
* Browser Name and version: Chrome 70.0.3538.67, Firefox 62.0.3, Edge 41.16299.611.0
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @tasinclair1 

can you check if updating Handsontable to 6.1.0 solves the issue?

**Comment by tasinclair1** [comment]
Hi @AMBudnik 

That seems to fix the issue but when I run Yarn install it throws a warning as the latest version of the angular wrapper only supports up to version 4.0.0 of handsontable.

```
warning " > @handsontable/angular@2.0.0" has incorrect peer dependency "handsontable@^4.0.0".
```

Will Handsontable 6.1.0 work with the wrapper with no issues if that is the advised solution?

Thanks.

**Comment by AMBudnik** [comment]
We are planning to update the version but haven't had time to test it properly. 
You still can use 6.1.0. We haven't been reported about any issues that relate to the use of higher Handsontable versions in the wrapper.

**Comment by tasinclair1** [comment]
Brilliant, thanks for your help!
