### ISSUE TITLE
Missing column and row headers on offscreen render

### ISSUE THREAD

**Issue by tasinclair1** [handsontable/angular-handsontable#135]
### Description
My application contains two tabs. One to configure the table (number of columns, number of rows and a few dynamic column header names) and another tab to display the table.

The tab content is held within two \<div> elements and the content is toggled using [hidden] attached to each \<div>.

As I configure the table, the table settings and data is continually updated.

By clicking on my "table" tab the configuration view will be hidden and the table view will be displayed by updating the [hidden] values on each.

The table will then appear with all data rendered in the cells correctly but the table will be missing it's column and row headers.

Expected -
![image](https://user-images.githubusercontent.com/5526949/49945171-2580d980-fee4-11e8-95a9-e6867a8e4217.png)

Actual -
![image](https://user-images.githubusercontent.com/5526949/49945117-fff3d000-fee3-11e8-94b1-aade6a855d13.png)

I believe I could solve my issue by using *ngIf rather than [hidden] but [hidden] works better for my use case due to the way that I am generating and then binding the data to the table.

I can force a render event by calling .render() on my table instance but I want to manually trigger this in code once [hidden] has been set to false on the table and the table is visible. It gets really messy trying to detect when the table is visible in Angular so I can force a render so I'd rather not go down this route if possible.

I've built a demo in StackBlitz that will showcase the issue using the same table settings as my own application.

### Steps to reproduce
Using the linked Stackblitz example -
1. Click "generate data"
2. Click "show"
3. Table should appear with all columns rendered exactly but missing the row and column headers
4. Clicking on the table will force a render event and the column rows and headers will appear.

### Demo
https://stackblitz.com/edit/handsontable-angular-rrnlhi

### Your environment
* Angular version: 7.1.3
* Handsontable version: 6.2.1
* Wrapper version: 2.0.0
* Browser Name and version: Chrome 70.0.3538.110
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @tasinclair1 

It looks the same as this issue https://github.com/handsontable/handsontable/issues/5685

Can you confirm?

**Comment by tasinclair1** [comment]
Hi @AMBudnik

Thanks for the update. It does look like the same issue as the headers do no appear when the table is initially rendered offscreen.

**Comment by AMBudnik** [comment]
Thank you for a prompt reply

**Comment by AMBudnik** [comment]
I think that we should stick to one issue so I am closing this one.

If we're missing something crucial in the second issue (#5685) please share a comment
