### ISSUE TITLE
Cannot install using NPM on windows

### ISSUE THREAD

**Issue by yehia2amer** [handsontable/angular-handsontable#14]
### Description

I am trying to install using **NPM** on windows but I always got this Error:

```
npm ERR! path C:\handsontableAngular\HandsontableAngularProj\node_modules\fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\handsontableAngular\HandsontableAngularProj\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\handsontableAngular\HandsontableAngularProj\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\handsontableAngular\\HandsontableAngularProj\\node_modules\\fsevents\\node_modules\\abbrev\\package.json\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\handsontableAngular\\HandsontableAngularProj\\node_modules\\fsevents\\node_modules\\abbrev\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amery\AppData\Roaming\npm-cache\_logs\2017-09-10T09_09_32_266Z-debug.log
```

### Steps to reproduce

1. Open PowerShell as **Administrator** 
2.  cd C:\handsontableAngular
3. ng new HandsontableAngularProj
4. npm install angular-handsontable

### Error Log
https://gist.github.com/yehia2amer/43fdf1edad27627cc21cb5bd7afae011

### Your environment
* **Wrapper version:** Handsontable for Angular (2+) - BETA 1 
* **Browser Name and version:** Firefox 55.0.3
* **Operating System:** Windows 10 Version 1607 (OS Build 14393.1480)
*  **node:** 6.11.3
*  **npm:** 5.4.1
*  **os:** win32 x64
*  **typescript:** 2.3.4
*  **angular/cli:** 1.4.1

**Comment by eitland** [comment]
I read through this yesterday and after re-reading it today the only relation I see between the error message and angular-handsontable is the name of the project.

This seems to be an error message from NPM that it cannot unlink "node_modules\fsevents\node_modules\abbrev\package.json"

While I cannot say fore sure this seems like a permission issue (yes, I read the part about opening PowerShell as Admin but Windows file permissions still has a way of surprising me ) or a file locking issue (I think some text editors and/or IDEs have a habit of grabbing files and keeping them open).

I run it as a non-admin user inside my user folder and it works fine except for the bugs around Zone etc.

**Comment by swistach** [comment]
Hi @yehia2amer,
I suppose it's the same error: npm/npm#18380
You can downgrade npm to v5.3. It should help on Windows.

**Comment by swistach** [comment]
I think we can close this issue.
