### ISSUE TITLE
Breaking Change: sortIndicator is no longer a valid input for hot-table

### ISSUE THREAD

**Issue by Calidus** [handsontable/angular-handsontable#141]
sortIndicator is no longer a valid input for hot-table, which is a breaking change from 
 @handsontable/angular 2.0 to @handsontable/angular 3.0 that isn't included in the release notes: https://handsontable.com/blog/articles/2018/12/handsontable-for-angular-is-now-3.0.0

### Your environment
* Angular version: 7.2
* Handsontable version: 6.2.2
* Wrapper version: 3.0

**Comment by AMBudnik** [comment]
Hey @Calidus 

the changes in the wrapper posts are only for the wrappers - not for the Handsontable PRO or CE. But, if we bump a version for the wrapper we should also place a link to the Handsontable version that we're set for the wrapper to load. Good catch!

**Comment by wojciechczerniak** [comment]
True, we can do that. But...

`@handsontable/angular` currently supports both (5.x and 6.x) versions of Handsonable. The hardcoded `sortIndicator` property in settings object https://github.com/handsontable/angular-handsontable/commit/8d7aec3da812d3794c70da7783d0be4a7ab0b970#diff-7d6a6dfa0f25734af57cce7ccb934098L16 was changed to settings that are based on Handsontable version you have installed https://github.com/handsontable/angular-handsontable/commit/8d7aec3da812d3794c70da7783d0be4a7ab0b970#diff-7d6a6dfa0f25734af57cce7ccb934098R4. In your case it will be v6.2.2 where `sortIndicator` was changed to `indicator`.

If you downgrade Handsontable the `sortIndicator` should be there.
