### ISSUE TITLE
Merge angular-handsontable packages into one

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/angular-handsontable#142]
### Description
We need to cleanup the split we have in the repository.

- [x] Single `readme.md` instead of three
  - [x] New readme: https://gist.github.com/krzysztofspilka/e24fffce134244cdc1bb206e7b6d8468
- [x] Single `license.txt` file instead of three
- [x] Change `contributing.md` title to Contributing to Handsontable for Angular
- [x] Update `contributing.md` content like we did it for react and vue: https://github.com/handsontable/react-handsontable/blob/master/CONTRIBUTING.md
- [x] Single `package.json` file instead of three
- [x] Merge keywords
- [x] Release: 06/03/2019
- [x] Deprecate `@handsontable-pro/angular`

https://gist.github.com/wojciechczerniak/0d8f74a34a05eaed01484f163a9b285b

Closes #86

**Comment by swistach** [comment]
Released in v4.0.0
