### ISSUE TITLE
registerCellType is missing in handsontable.d.ts

### ISSUE THREAD

**Issue by minchopm** [handsontable/angular-handsontable#143]
### Description
Please add support of registering of cellTypes in d.ts file

### Steps to reproduce
implement ```Handsontable.cellTypes.registerCellType```

**Comment by wojciechczerniak** [comment]
Done as a part of https://github.com/handsontable/handsontable/pull/5767

https://github.com/handsontable/handsontable/pull/5767/files#diff-1dc39ff18a8b67b43bd116052e584cc0R2036

Will be released in Handsontable 7.0.0
