### ISSUE TITLE
How to use custom renderers in angular-handsontable

### ISSUE THREAD

**Issue by GregFuntera** [handsontable/angular-handsontable#15]
How to properly use custom renderers for the cells in angular2
Do we use the same approach as the docs indicated https://docs.handsontable.com/pro/1.13.1/demo-custom-renderers.html.
Thank you

**Comment by swistach** [comment]
Hi @GregFuntera,
Unfortunately, currently we have not any example, how you can do this.
On the other hand you can try to use something like that: http://jsfiddle.net/8854ae5b/

**Comment by swistach** [comment]
Below is example how you can add a custom renderer (with an editors and an validators is similar):

**src/app/app.components.ts**
```ts
import { Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  settings = {
    renderer: function(hotInstance, td, row, column, prop, value, cellProperties) {
      // insert your custom renderer here
    }
  };
}
```

**src/app/app.component.html**
```ts
<hot-table [settings]="settings"></hot-table>
```

[Read more about custom renderers.](https://docs.handsontable.com/pro/demo-custom-renderers.html)
