### ISSUE TITLE
probem when table is in a if condition

### ISSUE THREAD

**Issue by brynnlow** [handsontable/angular-handsontable#151]
Hello I have some problem with the new @handsontable-angular: 4.0.0

my table is in a condition: *If 

<ng-container  *ngIf="viewTable">
  <hot-table [hotId]="2" [columns]="columns" [settings]="settings" [data]="persons"></hot-table>
</ng-container>

the first time he's instantiating everything is fine,

But when my *if become false then true the setting is not set properly anymore

its principally on the contextMenu and on the afterOnCellMouseDown 

At the original init my afterOnCellMouseDown work fine I receive the good value : 

afterOnCellMouseDown: (core, events, coords, td) 

Then my table disappears and reappears I receive 
afterOnCellMouseDown: (undefined, core, events, coords) 

The second time it disappears and reappears I receive 

afterOnCellMouseDown: (undefined, undefined, core, events) 

Third time it disappears and reappears I receive 

afterOnCellMouseDown: (undefined, undefined, undefined, core) 

for the contextMenu, it is only available on the first instance

Im trying to reproduce in stackblitz but on stackblitz it never reappears, only the first instance work

https://stackblitz.com/edit/angular-ugu92s?file=src%2Fapp%2Fapp.component.ts

navigator: chrome 73
handsontable: "7.0.0"
@handsontable/angular: "4.0.0"

**Comment by AMBudnik** [comment]
Hey @brynnlow if it does not happen in the online example it usually is related to other libraries and frameworks in the project. Have you tried to detach them to tests?

**Comment by brynnlow** [comment]
its not the problem who never reappears in the exemple but the table, try to click hide button twice



> preview-0b556b90ee0bcb987321b.js:1 ERROR TypeError: Cannot read property 'updateSettings' of undefined
    at init (app.component.ts:34)
    at eval (hot-settings-resolver.service.ts:48)
    at ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (ng_zone.ts:273)
    at ZoneDelegate.invoke (zone.js:390)
    at Zone.run (zone.js:150)
    at NgZone.run (ng_zone.ts:171)
    at eval (hot-settings-resolver.service.ts:48)
    at eval (hot-settings-resolver.service.ts:48)
    at ZoneDelegate.invoke (zone.js:391)
console.(anonymous function) @ preview-0b556b90ee0bcb987321b.js:1
17:27:58.358 preview-0b556b90ee0bcb987321b.js:1 Unable to display error. Open your browser's console to view.
console.(anonymous function) @ preview-0b556b90ee0bcb987321b.js:1
17:27:58.358 preview-0b556b90ee0bcb987321b.js:1 ERROR CONTEXT DebugContext_
console.(anonymous function) @ preview-0b556b90ee0bcb987321b.js:1
17:27:58.841 preview-0b556b90ee0bcb987321b.js:1 ERROR TypeError: Cannot read property 'destroy' of undefined
    at eval (hot-table.component.ts:360)
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:150)
    at NgZone.runOutsideAngular (ng_zone.ts:218)
    at HotTableComponent.ngOnDestroy (hot-table.component.ts:359)
    at callProviderLifecycles (provider.ts:575)
    at callElementProvidersLifecycles (provider.ts:541)
    at callLifecycleHooksChildrenFirst (provider.ts:529)
    at destroyView (view.ts:511)
    at callWithDebugContext (services.ts:629)

**Comment by AMBudnik** [comment]
You may want to use the [change ](https://angular.io/api/core/OnChanges)instead of init, but I do not guarantee it will work. We'd need to investigate this subject.

**Comment by brynnlow** [comment]
thanks you for looking, i will try to reproduce exactly my problem in a github exemple

**Comment by swistach** [comment]
Hi @brynnlow,
there are two connected issues:
1) I've solved a problem with the inconsistent arguments in hooks' callbacks - #123.
2) If hook's callback uses a reference to Handsontable instance before the end of this initialisation, then the reference is not defined. I'll solve it in PR.

Thank you for your involvement!

**Comment by daleclements** [comment]
I've encountered this issue as well using wrapper 3.0, handsontable 6.2, and Angular 6.

I managed to reproduce it in a stackblitz: https://stackblitz.com/edit/handsontable-angular-rhospe

**Comment by AMBudnik** [comment]
Hey @daleclements 
@swistach is already doing a great job to fix this issue. I'll ping you up as soon as we fix it and have the changes pushed to the official version of Handsontable.

**Comment by swistach** [comment]
Hi @brynnlow and @daleclements,
We've just released v5.0.0. Please try the new version and let us know about a result.
Here is @daleclements' demo with upgraded dependencies: https://stackblitz.com/edit/handsontable-angular-opy5sp?file=app/app.component.ts
