### ISSUE TITLE
Custom plugins in Angular 7

### ISSUE THREAD

**Issue by talamaska** [handsontable/angular-handsontable#153]
### Description
Following the guide for creating external custom plugins, we need to create a file that is based on the skeleton, it should contain the registerPlugin function. In order to make this work in Angular, we cannot have any imports at the top, meaning that handsontable should be included in the global scope. Following the guide from angular for global scripts we can include both the handsontable.js and the plugin in the angular.json app configuration sections scripts.
On the other side the angular component from handsontable is also having an import which is handled differently and basically creates a second instance of handsontable library which doesn't have the plugins attached.
The angular story https://github.com/angular/angular-cli/wiki/stories-global-scripts
says explicitly that if the library is included in the global scope it should not be imported.
I am requesting this import to be removed from the angular component wrapper.
Or expose a way to register plugins in angular because currenlty this is not possible.
And btw afterPluginsInitialized is not called.
I lost a day to figure out how to include a customPlugin in angular environment. Please act in a timely manner as my client has intend to by a license and this is not fixed in the v.4.0.0
There is no way to edit the webpack config.
I think you could do a conditional import with typescript. and verify if there is handsontable in the global scope if not then use require()

### Steps to reproduce

1. create a custom plugin say the example helloWorldPlugin and add a dellaration in your app component html
```
<hot-table [settings]="settings" [afterChange]="afterChange" [afterPluginsInitialized]="afterPluginsInitialized" [hotId]="uid" [afterInit]="afterInit"></hot-table>

```
2. include 
```
 "scripts": [
              "node_modules/handsontable/dist/handsontable.js",
              "plugins/helloWorldPlugin.js"
            ],
```
 in angular.json for your default app
3. in afterInit get the hotInstance and call getPlugin
```
  afterInit = (hotInstance) => {
    console.log('afterInit');
    this.hotInstance = hotInstance;
    console.log(this.hotInstance.getSettings());
    console.log(this.hotInstance.getPlugin<any>('helloWorldPlugin'));
  }
```
4. run the app
5. the table instance doesn't have the plugin attached
although when I add a breakpoint in the registerPlugin function it passed through and I see the plugin is attached.

The only way I made it work is to actually go to node_modules and remove the line 
``` import * as Handsontable from 'handsontable'; ``` from fesm5/handsontable-angular.js

### Your environment
* Angular version: 7.2
* Handsontable version: 6.2.2 (NOT PRO)
* Wrapper version: 3.0.0 (NOT PRO)
* Browser Name and version: Chrome/69.0.3497.128 Electron/4.0.7
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
> I think you could do a conditional import with typescript. and verify if there is handsontable in the global scope if not then use require()

thank you for the suggestion. 
To be honest, Skeleton hasn't been updated for a long time and we did not test it with the wrappers. But as we have more Clients using the wrappers we should consider altering the logic of Skeleton.

**Comment by talamaska** [comment]
The problem is not the skeleton, but the import in the angular component you have provided.
other than that, you might want to provide a way to attach a plugin from angular context, so that the instances are the same. Not sure about that.

**Comment by talamaska** [comment]
And this is tottaly not working on v4, I can't figure out how to add a custom plugin in the last version as the imports changed and my solution with the global inlude is not working anymore.

**Comment by AMBudnik** [comment]
Have you checked this demo https://stackblitz.com/edit/angular-pcimhx?file=src%2Fapp%2FcustomPlugin.ts that I got from our developer?
I've mentioned it here https://github.com/handsontable/handsontable/pull/5234

**Comment by talamaska** [comment]
Actually I've managed to rewrite the plugin as ES 2015 class and make the registration in onInit of my wrapping component. The example you are showing - first doesn't have any functionality and second I'm not sure how it will compile since 
![image](https://user-images.githubusercontent.com/299973/57014546-4048b600-6c19-11e9-99f3-746314e2a704.png)

**Comment by talamaska** [comment]
![image](https://user-images.githubusercontent.com/299973/57014715-f57b6e00-6c19-11e9-9147-77b362453e3a.png)
 and this, I'm not on my working PC, will check tomorrow, but 99% sure that this will not compile

**Comment by talamaska** [comment]
as expected the compilation fails.

```
ERROR in .../customPlugin.ts(16,35): error TS2339: Property 'call' does not exist on type 'Base'.
.../customPlugin.ts(35,82): error TS2339: Property 'prototype' does not exist on type 'Base'.
.../my-hot-table.component.ts(117,67): error TS2345: Argument of type 'typeof ExternalPluginSkeleton' is not assignable to parameter of type 'new (hotInstance?: Core) => Base'.
  Type 'typeof ExternalPluginSkeleton' provides no match for the signature 'new (hotInstance?: Core): Base'.
```

**Comment by AMBudnik** [comment]
Thank you for sharing the details. I'm very grateful. I think that it will help a lot of our users.
