### ISSUE TITLE
Performance issue when having lots of tree-component rows

### ISSUE THREAD

**Issue by ottosson** [handsontable/angular-handsontable#154]
### Description
I have an application where I use Handsontble and Angular-tree-component with lots of rows and columns in HoT and lots of rows in the tree.

When changing or selecting cells in HoT everything feels really sluggish (scrolling still feel super smooth and performant). I can set the ChangeDetectionStrategy to OnPush for the tree-component, but it the same doesn't make a difference for the HoT component... Are there any good practices to increase the performance of HoT? Can I do something similar to changing the ChangeDetectionStrategy?

### Demo
https://stackblitz.com/edit/handsontable-tree-component-performance

Thanks!

**Comment by AMBudnik** [comment]
Hey @ottosson 

I do not know how to help you here as once we remove the three-component Handsontable works faster. It looks like you get extra 1000 components that slow down the code. I do not think that this was the desired effect. What you'd like to achieve?

**Comment by ottosson** [comment]
Thank you. This is somewhat what I was thinking as well.

If I set ChangeDetectionStrategy for the tree to OnPush it will perform better, but HoT is still slow. Shouldn't this relieve the change detection mechanism for the whole app?

I guess this isn't really a HoT-problem, but I was hoping that there were some performance tricks I could use for the grid to speed it up. Or is this just an Angular related issue?

**Comment by AMBudnik** [comment]
I'm not an Angular expert but from a conversation with our programmer we came out to a conclusion that it can be an Angular issue. Especially when `ChangeDetectionStrategy` doesn't do you any favors.

**Comment by ottosson** [comment]
Right. I guess I'll follow that lead for now. Thanks for taking the time.
