### ISSUE TITLE
Angular 8 incompatible zone.js peer dependency 

### ISSUE THREAD

**Issue by frankie567** [handsontable/angular-handsontable#156]
### Description

When trying to migrate from Angular 7 to Angular 8, the Angular CLI complains that `@handsontable/angular` requires an incompatible `zone.js` version:

```
Package "@handsontable/angular" has an incompatible peer dependency to "zone.js" (requires "^0.8.19", would install "0.9.1").
```

We should consider allowing the `0.9` branch of `zone.js` to enable Angular 8 compatibility. 

### Steps to reproduce

1. Setup a working Angular 7 project with `@handsontable/angular`
2. Try to upgrade Angular: `ng update @angular/cli @angular/core`

### Your environment

* Angular version: 7.2.15 -> 8.0.0
* Handsontable version: 7.0.3
* Wrapper version: 5.0.0
* Browser Name and version: N.A.
* Operating System: macOS 10.14.4

**Comment by dhill2522** [comment]
I just ran into the exact same issue on a relatively large app. 

Would making a pull request for this be helpful or would it be better handled internally?

**Comment by AMBudnik** [comment]
Hey @dhill2522 

if you have an idea on how to fix it [while keeping code consistency](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) then we'd be more than happy to accept the PR :-)

**Comment by dhill2522** [comment]
Sounds good. I have some more pressing issues that came up now, but there is a chance I can get to this later. Don't wait on me though. 

Thanks to you and your team for providing a great package.

**Comment by santos222** [comment]
Are you planning to fix this in the community edition (v 6.2.2)? 

Echoing dhill2522, thanks for providing a great tool.

**Comment by AMBudnik** [comment]
Hey @santos222 since 7.0.0 Handsontable is only one product (PRO has been merged to CE) - `handsontable`. The `handsontable-pro` repository has been archived.
Besides, the wrappers releases are not related to Handsontable releases (and more or less its versions).

Our developer is already on it so it should be fixed soon.

**Comment by linktothapast** [comment]
Hi @AMBudnik. Thank you for the update. Do you have an estimate on when the fix could be available? So far only handsontable is preventing us from upgrading to ng8. Cheers

**Comment by AMBudnik** [comment]
The assigned developer is doing custom development for one of our Clients. It's on our Roadmap for this month so you can be sure that it'll be done as soon as possible.

**Comment by swistach** [comment]
Hi guys, v5.1.0 is released!
Thank you @frankie567 for your involvement!
