### ISSUE TITLE
import rxjs/Observable throw error when project doesn't use rxjs-compat

### ISSUE THREAD

**Issue by claudioaze** [handsontable/angular-handsontable#158]
### Description
handsontable.component.d.ts is importing Observable from 'rxjs/Observable', but it needs rxjs-compat dependency to work. 
I sugest to change it to import { Observable } from 'rxjs' to resolve problem if projects are not using rxjs-compat.

### Steps to reproduce

1. create a new angular-cli project
2. set handsontable dependency in your package.json
3. change app.component.spec.ts 
remove declarations: [AppComponent] 
and add imports: [AppModule]
run test and you will get error:
ERROR in node_modules/ng2-handsontable/handsontable.component.d.ts(2,10): error TS2305: Module '"../rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

### Your environment
* Angular version: 7.2.0
* Handsontable version: 2.1.0-rc.3
* Operating System: Windows 10 pro

**Comment by AMBudnik** [comment]
Hey @claudioaze 

can you .zip the project and send it over?

**Comment by claudioaze** [comment]
[angular-cli.zip](https://github.com/handsontable/angular-handsontable/files/3286303/angular-cli.zip)

**Comment by claudioaze** [comment]
> Hey @claudioaze
> 
> can you .zip the project and send it over?

Sure, here it is.
[angular-cli.zip](https://github.com/handsontable/angular-handsontable/files/3286306/angular-cli.zip)

**Comment by AMBudnik** [comment]
Our wrapper for Angular 2+ is here https://www.npmjs.com/package/@handsontable/angular and this is the only one that we support. https://www.npmjs.com/package/ng2-handsontable is not ours. As you can see in their repo that one was created by Valor software, not Handsontable.

**Comment by claudioaze** [comment]
> Our wrapper for Angular 2+ is here https://www.npmjs.com/package/@handsontable/angular and this is the only one that we support. https://www.npmjs.com/package/ng2-handsontable is not ours. As you can see in their repo that one was created by Valor software, not Handsontable.

sorry about that!
