### ISSUE TITLE
Custom editor throws error as shown in example with super(props)

### ISSUE THREAD

**Issue by seanlawrenz** [handsontable/angular-handsontable#160]
### Description

super(props) does not compile. 

The example below will work but as soon as you build the complier will reject it stating that was "Expected 6 arguments, but got 1."
### Steps to reproduce

1. Use example as listed on https://handsontable.com/docs/7.1.0/frameworks-wrapper-for-angular-custom-editor-example.html
2. Watch the error displayed on your IDE
3. Watch your app not get built.

### Demo

https://stackblitz.com/edit/handsontable-angular-f48mb8?file=app%2Fapp.component.ts

### Your environment
* Angular version: 7.2
* Handsontable version: 5.1.0
* Wrapper version: 5.1.0
* Browser Name and version: All.
* Operating System: MacOs

**Comment by AMBudnik** [comment]
Hey @seanlawrenz 

I did not get the error in the StackBlitz for any version ([Handsontable 5.1.0 doesn't exist](https://handsontable.com/docs/7.1.0/tutorial-release-notes.html)) on Windows/Chrome 76.

Can you check the latest version and let me know if it works for you?

**Comment by wojciechczerniak** [comment]
@AMBudnik Solved on forum: https://forum.handsontable.com/t/angular-custom-editor-example-has-errors/3521

**Comment by AMBudnik** [comment]
Great, thanks!
