### ISSUE TITLE
Unable to use router in the method passed to handsontable hooks

### ISSUE THREAD

**Issue by Iruora** [handsontable/angular-handsontable#162]
### Description
Unable to use router in the method passed to handsontable hooks, as if hot is not aware of all class elements even if it's using a class method as hook callback

### Steps to reproduce

1. Inject router in the component to use hot with
2. define a method as follows : 
```
test($event, coords, td) {
          const now = new Date().getTime();
          if (!(td.lastClick && now - td.lastClick < 200)) {
                td.lastClick = now;
               return; // no double-click detected
           }
          // double-click code goes here
          if (td.cellIndex === 0) {
              console.warn('id', td.innerText);
              this.selectedID  = td.innerText;
              this.router.navigate(['/elt'], {state: {id: this.selectedID}});
          }
    }
```
3. pass the method 'test' as a callback of Handsontable.hooks.add('afterOnCellMouseDown', this.test); in ngOnInit()

And then you'll see an error saying **"Cannot read property 'navigate' of undefined"**

### Your environment
* Angular version:
* Handsontable version: 7.1.0
* Wrapper version: 5.0.0
* Browser Name and version: Google Chrome Version 70.0.3538.67
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @Iruora 

Can you pass the Handsontable settings altogether in the demo https://jsfiddle.net/Lryd8kot/1/ and share it with me?

**Comment by swistach** [comment]
Hi @Iruora,
`Handsontable.hooks.add` adds callbacks to the global bucket and I'm pretty sure it's nothing that your application needs.

Although, if you want to add a callback to the instance, then you can add it using `hotInstance.addHook('afterOnCellMouseDown', (...args) => this.test(...args))` - `hotInstance` you can read from `HotTableRegisterer` https://handsontable.com/docs/frameworks-wrapper-for-angular-hot-reference.html 

Please let us know if it helped. If not, please provide a demo with the simplest configuration to reproduce this problem. I close this issue for now.

Feel free to reopen this issue if you're still facing the problem with adding callbacks in the wrapper.
