### ISSUE TITLE
Missing columns if a row is filled with large data

### ISSUE THREAD

**Issue by ndtung449** [handsontable/angular-handsontable#164]
### Description
When all cells of a row are filled with a large amount of data, only the first column is shown

### Steps to reproduce
1. Follow the example: https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-angular-simple-example.html
2. Remove the `[readOnly]` for the ID column in the template
3. On the browser, fill all cell of the first row (ID, Full name, and Street name) with 2000 letters "a"
4. On the last cell (Street name) use TAB to move to the first cell of the next row
5. Drag the horizontal scroll bar, all columns are disappeared except the first one

### Demo
https://stackblitz.com/edit/angular-tznhms

**Comment by AMBudnik** [comment]
Can you record the behavior @ndtung449 

I've tested it on Chrome 69/ Windows 10 and couldn't replicate the issue.

**Comment by ndtung449** [comment]
Hi @AMBudnik, this is the screen shot:
![hot-table-missing-columns](https://user-images.githubusercontent.com/27561025/64535335-4b3af200-d341-11e9-9cd8-b3eb17d7be08.png)
Chrome Version 76.0.3809.132 (Official Build) (64-bit)
Windows 10 Pro version 1809

**Comment by AMBudnik** [comment]
Please let me know what's the size of the window of the Handsontable window. I'm on the same system and browser and I cannot replicate it.

Do you have zoom applied?

**Comment by ndtung449** [comment]
Have you tried to fill all the cells of the first row (ID, Full name, and Street name)?
For every cell of the first row, enter 2000 letters "a", no white spaces. After filling the last cell, press TAB then drag the scroll bar and the issue should occur.

**Comment by AMBudnik** [comment]
Counted perfectly 2000 `a's` without spaces or other chars.

Here is what I got
![GIF](https://user-images.githubusercontent.com/10757813/64611653-3fe3d700-d3d2-11e9-93b0-78d7dc76e0fa.gif)

**Comment by ndtung449** [comment]
You should also fill the "Full name" with 2000 `a's` and the "Street name" with 2000 `a's`

**Comment by AMBudnik** [comment]
> You should also fill the "Full name" with 2000 a's and the "Street name" with 2000 a's

that's what I was missing. Then, yes - it shows only a single column.
I've checked other issues with the same description and it looks like this bug has been already defined here https://github.com/handsontable/handsontable/issues/3448 so I'm closing this topic but will keep the reference to check this demo after fixing.
