### ISSUE TITLE
unable to use your typings, nothing works

### ISSUE THREAD

**Issue by chrisrodriguezmbww** [handsontable/angular-handsontable#165]
### Description
None of your functions work!

### Steps to reproduce

1. type any function from Handsontable import
2. Handsontable.Core.prototype.getRowHeight(1)
3. handsontable__WEBPACK_IMPORTED_MODULE_2__.default.Core.prototype.getRowHeight is not a function

### Your environment
* Angular version: 7
* Handsontable version: 5.1

**Comment by AMBudnik** [comment]
Hi Chris,

I propose to check our examples on the page https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-angular-simple-example.html 
Some of the methods need plugins, others can be called[ for the Core ](https://handsontable.com/docs/7.1.1/frameworks-wrapper-for-angular-hot-reference.html)(which in this case is a Handsontable instance).

**Comment by swistach** [comment]
Hi @chrisrodriguezmbww,
I guess @AMBudnik's answer helped you to find information about how to call Handsontable's methods in our component. Feel free to reopen if you facing any problem with using Handsontable.Core methods in the wrapper.
