### ISSUE TITLE
Need documentation to use with handsontable pro

### ISSUE THREAD

**Issue by eitland** [handsontable/angular-handsontable#19]
### Steps to reproduce

1. I read the documentation. It says: 
```
Latest version 1.0.0-beta1, released on September 7th, 2017

Compatible with Handsontable Community Edition v0.34.1 and Pro v1.13.1
```
2. I continue to read the documentation. I still cannot figure out how I'm supposed to install them together without major hacks.

### Demo

See: https://handsontable.github.io/angular-handsontable/

### Your environment
* Wrapper version: n/a
* Browser Name and version: n/a
* Operating System: n/a

**Comment by AMBudnik** [comment]
Hi @eitland 

thank you for sharing your concerns.

Please let me know which step was misleading? Did you get any different results that mentioned in the docs?

**Comment by eitland** [comment]
Hi @AMBudnik, 

my fault and a bit embarrasing, it seems it is all described here: https://handsontable.github.io/angular-handsontable/use-with-pro 😬

**Comment by AMBudnik** [comment]
That's OK. I am happy that it's working :) 
ps. it's beta so feel free to share any concerns and questions.
