### ISSUE TITLE
Dynamic Columns With Ivy Compiler

### ISSUE THREAD

**Issue by jerms0518** [handsontable/angular-handsontable#192]
### Description
I am creating dynamic columns for my data and everything works fine with AOT **enabled** and [Ivy](https://angular.io/guide/ivy) **disabled**. With Ivy enabled, I receive this error while running `ng serve`: 
```
Type 'string' is not assignable to type 'any[][] | RowObject[]'
```

This error comes from the `Handsontable.GridSettings["data"]` type in `@handsontable\angular\lib\hot-column.component.d.ts`.

### Steps to reproduce (example attached below)
1. Create a new Angular CLI project using `ng new`.
2. Enable AOT for the project by setting `"aot": true` in `angular.json` for the web application.
3. Enable the Ivy compiler by adding the following section to the `tsconfig.app.json`:
```
  "angularCompilerOptions": {
    "enableIvy": true
  },
```
4. Create `<hot-column>` components using `ngFor` and set the `data` attribute using interpolation similar to this:
```
<hot-column *ngFor="let val of years; let i = index" data="{{ 'year' + (i + 1) }}" [width]="50" [title]="val"></hot-column>
```
5. In a terminal, run `npm install`.
6. In a terminal, run `npm start` to receive the compilation error.

### Demo
Working version (no Ivy and no error) on Stackblitz: https://stackblitz.com/edit/angular-handsontable-dynamic-columns

Example using same code with Ivy and AOT enabled (throws error): [hot-angular-dynamic-columns-ivy-aot.zip](https://github.com/handsontable/angular-handsontable/files/4149349/hot-angular-dynamic-columns-ivy-aot.zip)

### Your environment
* Angular version: 8.2.14
* Handsontable version: 7.3.0
* Wrapper version: 5.1.0
* Browser Name and version: Chrome Version 79.0.3945.130 (Official Build) (64-bit)
* Operating System: Windows 10 Enterprise, Version 1909

**Comment by AMBudnik** [comment]
Thank you for sharing @jerms0518 

Ivy has been introduced in Angular 8.0.0 as long as we support it we would need to get this done
https://angular.io/guide/ivy

> Ivy is the code name for Angular's next-generation compilation and rendering pipeline. Starting with Angular version 8, you can choose to opt in to start using a preview version of Ivy and help in its continuing development and tuning.

**Comment by jerms0518** [comment]
Any planned date for releasing the changes made for this issue?

**Comment by AMBudnik** [comment]
@jerms0518 it's one of our priorities. We should leave some updates soon.

**Comment by aninde** [comment]
Today we are testing a new version of `Angular-Handsontable 5.1.1` that should fix this problem.
 **How it was tested?** I installed in the project shared by @jerms0518 the new version of Angular-Handsontable and checked that the errors do not appear. 

@jerms0518 thank you very much for sharing the soup with an error. This greatly facilitates the work of the tester.

**Comment by AMBudnik** [comment]
@jerms0518 please update and share your feedback on **Handsontable for Angular 5.1.1**.

**Comment by jerms0518** [comment]
Yes, this does work now, even with Angular 9! Thank you!

**Comment by AMBudnik** [comment]
Thank you for feedback @jerms0518 
Let us know if you'd stumble into something unexpected. In the meanwhile, I keep my fingers crossed for your project :)
