### ISSUE TITLE
Our examples do not work on Edge

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/angular-handsontable#193]
### Description

The examples don't load but it seems to be related on what Angular is doing on Edge https://github.com/angular/angular/issues/26508

### Steps to reproduce

1. Just open the example in Edge
![image](https://user-images.githubusercontent.com/10757813/74220674-79d24580-4cb0-11ea-8c35-dd28548d8898.png)

### Demo

https://stackblitz.com/edit/handsontable-angular

### Your environment
* Angular version: 8.2.14
* Handsontable version: 7.3.0
* Wrapper version: 5.1.0
* Browser Name and version: Edge
* Operating System: Windows 10

**Comment by swistach** [comment]
It works with Handsontable v7.4.2 https://stackblitz.com/edit/angular-x8yjc3

**Comment by AMBudnik** [comment]
Great! I'm closing this issue.
