### ISSUE TITLE
Changing window size in CodeSandbox crashes Handsontable

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/angular-handsontable#194]
### Description
 Changing window size in CodeSandbox crashes Handsontable

### Steps to reproduce

1. Resize the example window

![angular](https://user-images.githubusercontent.com/10757813/74439633-e6923f00-4e6c-11ea-9660-39861d2ddaa9.gif)

### Demo

https://codesandbox.io/s/my-demo-uorsc Angular demo broken 😢 
https://codesandbox.io/s/date-dependent-time-change-jh9s3 Vanilla version working 👍 
https://codesandbox.io/s/react-ok-hn71u React version working 👍 
https://codesandbox.io/s/vue-ok-2cc54 Vue version working 👍 

### Your environment
* Angular version: 8.2.14
* Handsontable version: 7.3.0
* Wrapper version: 5.1.0
* Browser Name and version: Chrome 79
* Operating System: Mac Catalina

**Comment by aninde** [comment]
Should this not be reported in the examples [repo](https://github.com/handsontable/examples/)?

**Comment by AMBudnik** [comment]
I guess you're right. I've transferred the issue to https://github.com/handsontable/examples/issues/2
