### ISSUE TITLE
Update the wrapper for Angular 9 and Handsontable 7.4.0

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/angular-handsontable#195]
### Description
We need to check if Handsontable works correctly with newer Angular versions 8 and 9, with enable Ivy Compiler

- [x] Check Angular 9 compatibility
- [x] Check Angular 8 compatibility with optional Ivy flag
- [x] Dynamic Columns With Ivy Compiler #192 
- [x] Check window resize bug with ZoneNg https://github.com/handsontable/examples/issues/2
- [x] We will need an example for Codesandbox CI: https://github.com/handsontable/examples
- [ ] Change issue template example from Stackblitz to Codesandbox CI
- [x] Add Codesandbox CI to angular-handsontable repo as well

### Your environment
* Angular version: 8 and 9
* Handsontable version: 7.4.0
* Wrapper version: newer I guess
* Browser Name and version: Firefox 72
* Operating System: OS X

**Comment by swistach** [comment]
> Check window resize bug with ZoneNg handsontable/examples#2

It's actually a problem in `handsontable` itself, not in the wrapper. 😉

**Comment by NTXAggie** [comment]
Does this support angular 9 now?

**Comment by AMBudnik** [comment]
Hey @NTXAggie, not yet. But I will notify you once it's done.

**Comment by Kappyh** [comment]
Handsontable doesn't support angular 9? Or just Ivy compiler?

**Comment by AMBudnik** [comment]
Hi @Kappyh 
This issue should be already closed. We've added support for Angular 9 in Handsontable for Angular v5.1.1 https://github.com/handsontable/angular-handsontable/releases/tag/5.1.1
If you experience any issue on Angular 9 please let us know.
