### ISSUE TITLE
Unable to get hiddenRows (and trimRows) plugin

### ISSUE THREAD

**Issue by pnowak** [handsontable/angular-handsontable#196]
### Description
We can't use `hiddenRows` or `trimRows` in the Angular wrapper. 
If I change to another plugins e.g. `customBorders` or `manualColumnFreeze` we have access to options from these plugins. 
But mentioned plugins are not available, only `undefined`.

### Steps to reproduce

1. https://stackblitz.com/edit/angular-rddtah?file=src/app/app.component.ts
2. Open a console.

### Demo

https://stackblitz.com/edit/angular-rddtah?file=src/app/app.component.ts

### Your environment
* Angular version:
* Handsontable version:
* Wrapper version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
Both plugins are available in the latest release and the new one for v8. Should we close this @pnowak ?

https://jsfiddle.net/2u1exjvg/

**Comment by pnowak** [comment]
Yes, indeed.
So I close this issue.

Thanks @wojciechczerniak
