### ISSUE TITLE
Ng Build not working with Differential Loading

### ISSUE THREAD

**Issue by naveenjaiswal** [handsontable/angular-handsontable#198]
### Description
when building using "ng build" command with Differential Loading enables, the build is not working.
It throws the following error after  mins.
"An unhandled exception occurred: Call retries were exceeded"

### Steps to reproduce
1. npm install handsontable and handsontable/angular
2. In tsconfig.json , set "target": "es2015",
3. Build using command "ng build"

### Your environment
* Angular version: 8.2.14
* Angular CLI: 8.3.25
* Node: 10.16.3
* Handsontable version: 7.4.2
* Wrapper version: 5.1.0
* Browser Name and version:  chrome
* Operating System: win 10

**Comment by AMBudnik** [comment]
It works well on my device Windows,
npm v 6.11.3
node v 12.12.0
sys Windows 10 / FF 73
_________________________
_tsconfig.json_
```js
"target": "es2015",
```

_package.json_
```js
 "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@handsontable/angular": "^5.1.0",
    "core-js": "^2.5.4",
    "handsontable": "^7.4.2",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
```
![image](https://user-images.githubusercontent.com/10757813/75227875-4ebb1c00-57af-11ea-9c4e-eeb6393ebd3f.png)

![demo_2](https://user-images.githubusercontent.com/10757813/75228166-f5072180-57af-11ea-881f-04bb75054702.gif)

Can you send over a .zip @naveenjaiswal ?

**Comment by wojciechczerniak** [comment]
No response. Please reopen with more details
