### ISSUE TITLE
error TS2339: Property 'x' does not exist on type 'GridSettings' in Angular 9 and handsontable 6.2.2

### ISSUE THREAD

**Issue by skobak** [handsontable/angular-handsontable#201]
### Description

Typescript error:
such as:

> error TS2339: Property 'beforeTrimRow' does not exist on type 'GridSettings'.
> error TS2339: Property 'beforeUnhideColumns' does not exist on type 'GridSettings'.
and etc....

It should build the project without errors.

Is the new version 5.1.0 is compatible with handsontable 6.2.2 (community edition) ?

### Steps to reproduce

1. Was working ok before the update from Angular 7 -> Angular 9 and wrapper version till latest 5.1.0
2. Build become failed after update 

### Your environment
* Angular version: 9.0.5
* Handsontable version: 6.2.2
* Wrapper version: 5.1.0
* Browser Name and version: Chrome Version 80.0.3987.122 (Official Build) (64-bit)
* Operating System: Windows

**Comment by pnowak** [comment]
We are pretty aware of this matter. Please track the progress of this issue - https://github.com/handsontable/angular-handsontable/issues/195.
