### ISSUE TITLE
Facing problem while using Hidden columns along with flexibilty to move visible columns

### ISSUE THREAD

**Issue by saurabhpandey2010** [handsontable/angular-handsontable#202]
### Description
Expected-
When using the HandsonTable , i want to use hidden columns and the flexibilty to move the visible columns in Angular 7 application. Is it possible to use both the functionality together and any sample present over jsfiddle?

Current behaviour-
When visible columns are moved over hidden columns, the value of columns become blank and again moving away from hidden columns the values becomes visible

### Steps to reproduce
In the example below-
1. Columns are hidden - D,F,J
2. Select two visible columns and move over hidden columns
3. The Visible columns values become blank
4. When moving the values of visible columns should not become blank.

### Demo
example - https://jsfiddle.net/enwLmg80/

### Your environment
* Angular version: 7
* Handsontable version: handsontable@7.0.3
* Wrapper version: --
* Browser Name and version: Chrome
* Operating System: Win 7

**Comment by AMBudnik** [comment]
Hi @saurabhpandey2010 

this issue has been reported for the vanilla version https://github.com/handsontable/handsontable/issues/5598 and should be fixed in the stable `8.0.0`

I will update you once it happens.
