### ISSUE TITLE
Growing DOM nodes during mouse moving 

### ISSUE THREAD

**Issue by skobak** [handsontable/angular-handsontable#204]
### Description
When 'hot-table' placed in a component you can see a pump of DOM nodes in the performance monitor tab in the Chrome Dev Tool. Moreover, just by moving the mouse, you can see a rapid increase of DOM nodes without any visual changes.  When you have  1000 cells or more, you can have a 'freezing' experience on UI  at the start until garbage collection will not drop the amount of DOM nodes

**Desired state:**
When data loaded and rendered amount of DOM nodes stay stable like in Vue or React example.
When the mouse is moving in a window with 'hot-table' component, DOM nodes stay stable

### Steps to reproduce
You can see it at official docs :
 https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-angular-simple-example.html
1. Open two tabs in the  handsontable documentation, one for Angular Wrapper and one for React or Vue
2. Open Chrome Dev Tools, and Performance monitor  (f12 -> ctrl+P -> '>perfomance monitor')
3. Start moving mouse around on both tabs and look and parameter DOM nodes

### Demo
You can see on official docs
 https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-angular-simple-example.html
I haven't found a way to reproduce it on Stackblitz, probably due to how Performance Monitor works

1. Download data from DB and loadData to a hot instance
2. Then user move the mouse with no actions, the amount of DOM nodes also growing until Garbage collection will clean it

### Your environment
* Angular version: 7.2
* Handsontable version: 6.2.2
* Wrapper version: 3.0
* Browser Name and version: Chrome 81
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @skobak 

Can you share a recording? Do you use any addons/apps for Chrome?

**Comment by skobak** [comment]
Hi @AMBudnik, thank you for the quick response.

I test it in incognito mode, with no Chrome extensions
[ezyzip.zip](https://github.com/handsontable/angular-handsontable/files/4573944/ezyzip.zip)

I also found my own bug in my system that was lead to 'freezing' experience, but the question about growing nodes on mouse move I decided to leave here

**Comment by AMBudnik** [comment]
Thank you for sharing the video, Aleksandr.

You're right - Angular is the only implementation where the number of nodes increments on the hover. However, I can see that the number drops when we hit around 10k to 9.2k, and then it repeats (builds to 10k and drops to 9.2k). Used demo https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-angular-simple-example.html

@wojciechczerniak what do you think?

**Comment by skobak** [comment]
Yes you right, the garbage collector clean it periodically, and the top  nodes number I guess it depends on the size of visual data (zoom ratio or screen size) and  **viewportRowRenderingOffset**
