### ISSUE TITLE
nestedHeaders are a bit misaligned and are missing one border.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/angular-handsontable#205]
### Description

`nestedHeaders` are a bit misaligned and are missing one border in Angular.

It looks like this
![Zrzut ekranu 2020-05-22 o 11 21 38](https://user-images.githubusercontent.com/10757813/82652745-6d9a4480-9c1e-11ea-9985-81d849e55736.png)

Here is how it looks in Vanilla, React, and Vue.
![Zrzut ekranu 2020-05-22 o 11 22 34](https://user-images.githubusercontent.com/10757813/82652823-8c98d680-9c1e-11ea-81aa-e270a507a962.png)

### Steps to reproduce

1. No steps required. The result is visible after page loads.

### Demo

https://codesandbox.io/s/setdataatcell-settimeout-external-call-in-angular-3esgs angular **broken**
https://jsfiddle.net/AMBudnik/sova97cw/ vue ok
https://jsfiddle.net/AMBudnik/y7tjLgd6/ vanilla ok
https://jsfiddle.net/AMBudnik/vdb453wt/ React ok

### Your environment
* Angular version: 8
* Handsontable version: 7.4.2
* Wrapper version: 5.1.1
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by wojciechczerniak** [comment]
Looks like it's fixed in Handsontable v8 and Angular Wrapper v6-candidate #211 

![Screenshot 2020-07-28 at 00 47 47](https://user-images.githubusercontent.com/4718998/88599414-fc3aa000-d06b-11ea-9e0e-00aa4b9f7997.png)


@AMBudnik should be rechecked after the release

**Comment by AMBudnik** [comment]
@wojciechczerniak you're right the issue is no longer replicable when we use v8 https://jsfiddle.net/ojkhs2c7/.
We can close it as solved.
