### ISSUE TITLE
[8.0.0-beta2-rev7] some properties doesn't exist on type GridSettings

### ISSUE THREAD

**Issue by aninde** [handsontable/angular-handsontable#207]
### Description
Some properties missing on type GridSettings in Handsontable, so you can't build an application in angular and run it through Angular CLI. 

**Browser:**
<img width="1366" alt="Screenshot 2020-05-22 at 17 35 24" src="https://user-images.githubusercontent.com/30186818/82684302-a6eca780-9c52-11ea-92dd-511a4d8e48d3.png">

**Console:**
ERROR in node_modules/@handsontable/angular/lib/hot-table.component.d.ts:53:38 - error TS2339: Property 'debug' does not exist on type 'GridSettings'.

node_modules/@handsontable/angular/lib/hot-table.component.d.ts:276:42 - error TS2339: Property 'modifyCol' does not exist on type 'GridSettings'.

node_modules/@handsontable/angular/lib/hot-table.component.d.ts:283:42 - error TS2339: Property 'modifyRow' does not exist on type 'GridSettings'.

node_modules/@handsontable/angular/lib/hot-table.component.d.ts:293:48 - error TS2339: Property 'skipLengthCache' does not exist on type 'GridSettings'.

node_modules/@handsontable/angular/lib/hot-table.component.d.ts:294:44 - error TS2339: Property 'unmodifyCol' does not exist on type 'GridSettings'.

node_modules/@handsontable/angular/lib/hot-table.component.d.ts:295:44 - error TS2339: Property 'unmodifyRow' does not exist on type 'GridSettings'.

![Screenshot 2020-05-22 at 17 33 31](https://user-images.githubusercontent.com/30186818/82684154-6db43780-9c52-11ea-9afa-adaf9eaa7fca.png)

### Your environment
* Angular version: 8 + Angilar CLI 9.1.4 
* Handsontable version: 8.0.0-beta2-rev7
* Wrapper version: 5.1.1
* Browser Name and version: Firefox
* Operating System: macOs Mojave

**Comment by wojciechczerniak** [comment]
Part of #197
