### ISSUE TITLE
[Angular2+handsontable-pro]@handsontable-pro\angular build Error!!

### ISSUE THREAD

**Issue by k-ryu** [handsontable/angular-handsontable#208]
### Description

I've got the flllowing build error(hot-column.component.d.ts:7:42']' expected.) i don't know if there is a problem with the handsontable version or if there is sth wrong in my source.

 90% optimize assetsError in bail mode: [default] C:\pro_workspace_prod\pro-handsontable\pro-Int\src\main\web-builder\node_modul
es\@handsontable-pro\angular\lib\hot-column.component.d.ts:7:42
']' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pro-Int@1.0.0 build_secure: `rimraf ../webapp/secure && webpack --display-error-details --config config/webpack.secure.dev.js
 --progress --colors --profile --bail -d`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pro-Int@1.0.0 build_secure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\id\AppData\Roaming\npm-cache\_logs\2020-06-02T00_48_56_202Z-debug.log

### src

[handsontable-test-question.zip](https://github.com/handsontable/angular-handsontable/files/4714233/handsontable-test-question.zip)

### package json
{
  "name": "pro-Int",
  "version": "1.0.0",
  "bin": {
    "dev": "startup.bat"
  },
  "description": "A webpack starter for aeroInternal",
  "scripts": {
    "dev": "gulp build_login",
    "build_login": "gulp build_login",
    "build_login_prod": "gulp build_login_prod",
    "dsr": "gulp download_server_resources",
    "sec_dev": "rimraf ../webapp/secure && webpack --display-error-details --config config/webpack.secure.dev.js --progress --colors --profile --bail -d",
    "build_secure": "rimraf ../webapp/secure && webpack --display-error-details --config config/webpack.secure.dev.js --progress --colors --profile --bail -d",
    "build_secure_prod": "gulp build_secure_prod"
  },
  "dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "@handsontable-pro/angular": "^3.0.1",
    "admin-lte": "2.3.8",
    "angular2-modal": "^2.0.2",
    "bootstrap": "^3.3.6",
    "bootstrap-datepicker": "^1.6.4",
    "core-js": "^2.4.1",
    "datatables.net": "^1.10.12",
    "datatables.net-bs": "^1.10.12",
    "datatables.net-buttons": "^1.2.2",
    "datatables.net-buttons-bs": "^1.2.2",
    "datatables.net-colreorder": "^1.3.2",
    "datatables.net-colreorder-bs": "^1.3.2",
    "datatables.net-keytable": "^2.1.3",
    "datatables.net-keytable-bs": "^2.1.3",
    "datatables.net-select": "^1.2.0",
    "datatables.net-select-bs": "^1.2.0",
    "dynamic-module-loader": "^1.0.8",
    "eventsource": "^0.2.1",
    "font-awesome": "^4.7.0",
    "fs-extra": "^1.0.0",
    "handsontable-pro": "^6.2.3",
    "icheck": "^1.0.2",
    "ionicons": "^2.0.1",
    "jquery": "^2.1.4",
    "jquery-slimscroll": "^1.3.8",
    "minimatch": "^3.0.3",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "slimscroll": "^0.9.1",
    "xlsx": "^0.14.4",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "angular2-router-loader": "^0.3.4",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "^2.2.4",
    "css-loader": "^0.23.1",
    "del": "^2.2.2",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "gulp": "^3.9.1",
    "gulp-download-stream": "0.0.13",
    "gulp-json-editor": "^2.2.1",
    "gulp-plumber": "^1.1.0",
    "gulp-streamify": "^1.0.2",
    "gulp-util": "^3.0.7",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "moment": "^2.10.3",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.14",
    "raw-loader": "^0.5.1",
    "request": "^2.78.0",
    "rimraf": "^2.5.4",
    "run-sequence": "^1.2.2",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.5",
    "typescript": "2.0.10",
    "typings": "^1.3.2",
    "url-loader": "^0.5.7",
    "vinyl-source-stream": "^1.1.0",
    "webpack": "^1.13.3",
    "webpack-livereload-plugin": "^0.9.0",
    "webpack-merge": "^0.14.0"
  }
}

### Your environment
* Angular version:2.1.0
* Handsontable version:handsontable-pro": "^6.2.3",
* Wrapper version:
* Browser Name and version: chome
* Operating System: win10

**Comment by pnowak** [comment]
Hi @k-ryu 

As you can see `@handsontable-pro/angular` has been deprecated - https://www.npmjs.com/package/@handsontable-pro/angular

Could you update our wrapper for Angular and test then it against this issue?

**Comment by wojciechczerniak** [comment]
No response. Please reopen with more details.
