### ISSUE TITLE
custom renderer columns value not binding with data

### ISSUE THREAD

**Issue by LucasDGomez** [handsontable/angular-handsontable#209]
### Description

custom renderer columns value not binding with data.

All columns without custom render binding ok.

column with custom renderer example:

 {
      data: 'NroItem',
      readOnly: true,
      type: 'numeric',
      renderer: (instance, TD, row, col, prop, value, cellProperties) => {
        TD.innerHTML = (row + 1).toString();
        return TD;
      },
    },

I can't even get this data with getDataAtCell

**Comment by AMBudnik** [comment]
Hi @LucasDGomez 

Can you share some details? I've used you data and it seems to work well https://jsfiddle.net/9ta3po15/1/

**Comment by AMBudnik** [comment]
If you'd have any issues with that code please let me know on emails support@handsontable.com
