### ISSUE TITLE
Uncaught Error: Unknown culture : es-ES

### ISSUE THREAD

**Issue by vadimkent** [handsontable/angular-handsontable#21]
### Description

I've got this error when changing a Column language to anything different from en-US

Debugging in chrome i can see the cultures array with only en-US, and a function 'loadCulturesInNode' intended to load cultures that is never called.

When this function is called from console being stopped in a breakpoint everything works OK.

### Steps to reproduce

1. Start a new Angular CLI project and follow the quickstart to the point. ( added an aditional import 'angular-handsontable'; in polyfills in order to make it work)
2. Populate columns from component, with language configured as 'es-Es'
3. Edit a cell value

### Your environment
* Angular version: 4.2.4
* Angular CLI version: 1.3.2
* Wrapper version: 1.0.0-beta2
* Browser Name and version: Chrome 60.0.3112.113

**Comment by AMBudnik** [comment]
At the first glance, it looks like the language.js file is missing. Have you added it to the build?

**Comment by vadimkent** [comment]
I've just included the language.js file and still got the same error.

I added it in the .angular-cli.json file as follows and ensured that the generated scripts are included in the index.

`"scripts": [
            "../node_modules/handsontable/dist/numbro/languages.js"
        ],`

Thanks for your answer!

**Comment by AMBudnik** [comment]
At the first glance, it looks like everything should work, however, I am not an expert. I will ask @swistach as soon as he'll be back (on Monday).

**Comment by swistach** [comment]
Hi @vadimkent,
Unfortunately, `numbro` is not ideal. Perhaps, the similar solution as in `momentjs` could be helpful to try resolve this issue.

**Comment by vadimkent** [comment]
Hi @swistach,

Thanks for your answer. What do you mean with a similar solution as in `momentjs`?

**Comment by AMBudnik** [comment]
Hi @vadimkent 

it means that the cell that controls `date` may also cause some issues (it uses the moment.js)

**Comment by isak-spinit** [comment]
Did you solve this? I have the same problem.
In the handsontable bundle index.umd.js, I can see that the list of languages but they are never loaded into the cultures array.
loadCulturesInNode() is never called because inNodejsRuntime() returns false.

**Comment by jyriketonen** [comment]
I have the same problem. Any workaround for this?

**Comment by Frull** [comment]
@AMBudnik, @swistach what is the status on this issue? 
It is marked as Answered/Bug. Could we get a hint if it is something that will be resolved soon? Any suggested workarounds?

**Comment by AMBudnik** [comment]
I think that @swistach wanted to tell that this should be fixed. However, it would take a significant amount of research in the first place. Am I right @swistach?

**Comment by alarie** [comment]
This is most likely an issue of the language files in combination with webpack. The files export their languages as object and/or register them as culture due to this code:

```
    // de-DE.ts
    // ...
    // Node
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = language;
    }
    // Browser
    if (typeof window !== 'undefined' && window.numbro && window.numbro.culture) {
        this.numbro.culture('bg', language);
    }
```

If using webpack with a module system like commonjs or other `window.numbro` won't be defined and thus the `// Browser` lines don't get executed. Thus the languages are never registered as such within numbro. To circumvent that you can register them yourself, for example: 

```
import numbro from "numbro"
import * as languages from "numbro/languages"
Object.keys(languages).forEach((lang) => {
  numbro.culture(lang, languages[lang])
})
```

**Comment by AMBudnik** [comment]
Thank you for sharing your investigation result @alarie

**Comment by swistach** [comment]
Hi @vadimkent,
sorry for the delay, I mean almost the same thing as @alarie (Thanks for your investigation).
Even if we import languages in our component, still we have no access to register next culture inside Handsontable, actually in `numericRenderer`.

**Comment by swistach** [comment]
Hi @vadimkent.
In the latest version of Handsontable (4.0.0), we used the newest Numbrojs. Now you can use more cultures in your project.
Here is a simple example: https://stackblitz.com/edit/handsontable-angular-numbrov2?file=src/app/app.component.ts

Feel free to reopen, if it is still an issue.
