### ISSUE TITLE
Cannot get hot instance by hotRegisterer

### ISSUE THREAD

**Issue by lhf552004** [handsontable/angular-handsontable#210]
### Description
The handsontabl cannot show.  In the console, there are two errors.
1.  ERROR TypeError: Cannot read property 'nativeElement' of undefined,  at handsontable-angular.js:148
     This error occured when loading the <hot-table> tag. As it happend after excuting ngOnInit() , but before ngAfterViewInit();
2.  ERROR TypeError: Cannot read property 'updateSettings' of undefined
     This error is due to get hot instance failed by hotRegisterer when executing 
     
```
     getHotInstance(instance: string): Handsontable {
        return this.hotRegisterer.getInstance(instance);
     };
```
![image](https://user-images.githubusercontent.com/10030850/85966615-e39a8400-b9f2-11ea-9072-3975df10574c.png)

Detail please see demo. Thanks

### Demo

https://stackblitz.com/edit/angular-handsontable-testing

### Your environment
* Angular version:  9.1.9
*   "@handsontable/angular": "^3.0.0",
    "handsontable": "^6.2.2",
* Wrapper version:
* Browser Name and version: Chrome@81
* Operating System: Windows10

**Comment by pnowak** [comment]
Hi @lhf552004 

First of all, you can use Angular 9 only with `@handsontable/angular 5.1.1`. 

Nevertheless, even with the updated angular wrapper we still have some issue. You declare `hot: Handsontable;` but then you use `hot` as a string - `this.getHotInstance('hot');`. Besides this declaration isn't an instance declaration. 

Here is a link to our docs about how to reference the Handsontable instance from the wrapper component - https://handsontable.com/docs/7.4.2/frameworks-wrapper-for-angular-hot-reference.html
As you can see, in `.hml` we set id - `[hotId]="id"`, and next reference to it by `id = 'hotInstance';`. Then we use it `this.hotRegisterer.getInstance(this.id)` to get the instance of Handsontable.

Unfortunately, after these fixes we still have an error - `Cannot read property 'nativeElement' of undefined`. I think that you have to build hot-table first and only then reference to its. So `AfterViewInit` is too early to this type of operations.

**Comment by lhf552004** [comment]
OK @pnowak , thanks.
