### ISSUE TITLE
Update ModuleWithProviders for Angular 10

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/angular-handsontable#212]
### Description

ModuleWithProviders generic was deprecated in Angular 9 and removed in Angular 10.

https://next.angular.io/guide/migration-module-with-providers

https://github.com/handsontable/angular-handsontable/blob/33d1f1f8d33caedf2b3575377730e357aeae5190/projects/hot-table/src/lib/hot-table.module.ts#L26-L33

```diff
export class HotTableModule extends Version {
-  public static forRoot(): ModuleWithProviders {
+  public static forRoot(): ModuleWithProviders<HotTableModule> {
    return {
      ngModule: HotTableModule,
      providers: [ HotTableRegisterer ],
    };
  }
}
```

### Steps to reproduce

1. Create new app with angular CLI version 10
2. Use our readme.md to install Handsontable and wrapper
3. There is an error about ModuleWithProviders generic type 

### Your environment
* Angular version: 10
* Handsontable version: 8.0.0-rc
* Wrapper version:  #211
* Browser Name and version: Firefox
* Operating System: OS X

**Comment by jansiegel** [comment]
Resolved in #211.
