### ISSUE TITLE
Using `updateSettings` within 6.0.1 with 8.0.0 cause an issue.

### ISSUE THREAD

**Issue by pnowak** [handsontable/angular-handsontable#213]
### Description
It seems that we have an issue with version 8.0.0 Handsontable within Angular wrapper to 6.0.1 - 
https://codesandbox.io/s/setdataatcell-settimeout-external-call-in-angular-800-handsontable-and-angular-wrapper-to-601-j0jfr
![Zrzut ekranu 2020-08-21 o 12 42 51](https://user-images.githubusercontent.com/1555809/90882204-e474e400-e3ab-11ea-81b8-b2b4b43ec7bd.png)

The previous version of Handsontable 7.4.2 within Angular wrapper to 6.0.1 works well - https://codesandbox.io/s/setdataatcell-settimeout-external-call-in-angular-742-handsontable-and-angular-wrapper-to-601-8gtxw?file=/src/app/hello.component.ts

### More information
https://github.com/handsontable/support/issues/211

### Your environment
* Angular version: 7.0.0
* Handsontable version: 8.0.0
* Wrapper version: 6.0.1
* Browser Name and version:
* Operating System:

**Inform Zen 25313**

**Comment by wojciechczerniak** [comment]
Will be fixed in handsontable/handsontable#7228

**Comment by wojciechczerniak** [comment]
@AMBudnik @pnowak Can we re-test this with `v8.1.0` and inform the support ticket author?

**Comment by pnowak** [comment]
Yes, it works well - https://codesandbox.io/s/setdataatcell-settimeout-external-call-in-angular-810-handsontable-and-angular-wrapper-to-601-c63we

**Comment by AMBudnik** [comment]
Thanks for checking. I've updated the Client. 
We can close the issue as solved.
