### ISSUE TITLE
use api to get data dynamically

### ISSUE THREAD

**Issue by gargri** [handsontable/angular-handsontable#214]
how i can use api or url so that i can get data from api

**Comment by AMBudnik** [comment]
Hi @gargri 

here https://handsontable.com/docs/8.0.0/frameworks-wrapper-for-angular-hot-reference.html is an example that shows you how to get and load data using Handsontable for Angular.

I will be happy to answer any questions you may have about the implementation.

**Comment by gargri** [comment]
thanku for reply ...
there is any way to use url, i want to get data from json file ,
in file data is save in json format ..
 can u give me any idea how i can add that file or url

**Comment by AMBudnik** [comment]
Hi @gargri 

here's a JSON example http://jsfiddle.net/AMBudnik/Lz4achdb/
I do not have any online JSON file to use a real link but if you have any and it won't work for please send the sample to me at support@handsontable.com
