### ISSUE TITLE
cell dropdown opens but when click outside or on selection of any value from dropdown it doesn't close.

### ISSUE THREAD

**Issue by paras-deshbhratar** [handsontable/angular-handsontable#217]
### Description

On double clicking grid cell, dropdown opens up, but when value is selected from dropdown or clicked outside, dropdown should close.

### Steps to reproduce

1. click on any cell under 'Position' column.
2. dropdown opens, select any value from dropdown.
3. try clicking outside of dropdown.

### Demo

https://stackblitz.com/edit/angular-handsontable-dropdown

### Your environment
![handsontable-dropdown-bug](https://user-images.githubusercontent.com/27829343/94552721-f1230c80-0274-11eb-9aa3-94e8d232e566.JPG)

* Angular version: ~9.1.9
* Handsontable version: ^8.0.0
* Wrapper version: ^6.0.1
* Browser Name and version: Chrome 85.0.4183.102 (Official Build) (64-bit)
* Operating System: Windows 10 (64-bit)

**Comment by AMBudnik** [comment]
We covered this subject on emails with the Client.
