### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by fbaldo31** [handsontable/angular-handsontable#220]
### Description
@angular v10 as peerDependies

### Your environment
* Angular version: 10
* Handsontable version: 8.1.0
* Wrapper version: 6.0.1

Is there any reason to have v8 support only in package.json ?

**Comment by AMBudnik** [comment]
Hi @fbaldo31 ,

Angular 10 should be fully supported after the changes made in https://github.com/handsontable/angular-handsontable/issues/212 
If you experience any inconvenience please let me know here on the Github board or on my support email (support@handsontable.com)
