### ISSUE TITLE
Is that possible to use wrapper with Angular 8 and Handonstable 6.2.2. (community edition)?

### ISSUE THREAD

**Issue by skobak** [handsontable/angular-handsontable#221]
I saw you have added support for Angular 8 in 5.0.1, but also switch to Handonstable 7+ which is commercial now. 
The question is are we locked with angular 7 if we do not want to change the license in handonstable 7?

Thanks for your wrapper!

**Comment by wojciechczerniak** [comment]
Handsontable is a `peerDependency` so you may try to install the wrapper v5.0.1 with Handsontable 6.2.2. Just ignore the NPM warning about version mismatch.

But I doubt it will work correctly. This is the only wrapper for Handsontable that is strongly typed. The update to v7+ involved API changes so it may not compile correctly with any other version.

Fork should work. Fork the wrapper (it's MIT licensed) and restore old API types from the history and keep the changes for Angular 8 support.
