### ISSUE TITLE
"ERROR TypeError: this.indexesSequence.addLocalHook is not a function" after Serve Static in nestjs server

### ISSUE THREAD

**Issue by bioShaun** [handsontable/angular-handsontable#223]
### Description

The Basic example in document works fine in the angular serve mode.
However, when I use nestjs serve static the build dist, it showed "ERROR TypeError: this.indexesSequence.addLocalHook is not a function".

### Steps to reproduce

1. build and serve static in nestjs server

### Your environment
* Angular version:10.1.3
* Handsontable version:8.3.0
* Wrapper version:6.0.1
* Browser Name and version:firefox 84.0.2
* Operating System:ubuntu 20.04

**Comment by yatinagrawal** [comment]
I am facing this exact issue..

local build serve is working fine..

when i make prod bundle this error appears..

how do i solve it

**Comment by AMBudnik** [comment]
Thank you for sharing the issue.
We can keep the conversation here https://github.com/handsontable/angular-handsontable/issues/223 not to duplicate the reports.

(note to myself inform [forum](https://forum.handsontable.com/t/angular-223-error-on-server/4984/3))
