### ISSUE TITLE
Access to Handsontable instance with Angular2 wrapper

### ISSUE THREAD

**Issue by kunalmkamble** [handsontable/angular-handsontable#24]
### Description
Unable to inject HotRegisterer to component

### Steps to reproduce
I am referring the "Set up a component" section from https://handsontable.github.io/angular-handsontable/examples/access-to-handsontable. Below error is displayed on the console just by injecting HotRegister to a component. 

### Stacktrace
I am getting following error. 
Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise (window|global).Promise has been overwritten. 
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.) 
at Function.Zone.assertZonePatched (zone.js:44) 
at new NgZone (core.es5.js:3973) 
at PlatformRef_._bootstrapModuleFactoryWithZone (core.es5.js:4767) 
at core.es5.js:4812 
at run (index.umd.js:33758) 
at index.umd.js:33771 
at MutationObserver.flush (index.umd.js:65715) 
at ZoneDelegate.invoke (zone.js:391) 
at Zone.runGuarded (zone.js:154) 
at MutationObserver. (zone.js:132)

### Your environment
* Wrapper version: 1.0.3
* Browser Name and version: Chrome Version 60
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Hi @kunalmkamble 

The issue seems to be the same as mentioned at #17
Can you confirm that?

**Comment by kunalmkamble** [comment]
Issue is same but the trigger is point are different. I am facing this issue when I am trying to access the instance of the Handsontable. 
Still I went ahead an applied the solution mentioned in #17. It resolved the issue, but pro features stopped working. 

After debugging the issue I have narrowed down to following cases

If I use 
import { HotTableModule } from 'angular-handsontable';
Pro features does not work

If I use 
import { HotTableModule } from 'angular-handsontable/index';
End up getting following error on console
Error: No provider for HotRegisterer!

**Comment by AMBudnik** [comment]
I have to say that I am not familiar with the following bug

`No provider for HotRegisterer!`

@swistach will be back on Monday and will check what can be the cause

**Comment by kunalmkamble** [comment]
Hello @swistach could please address this, this is a blocker issue for us for the last whole week. We are not able to use few pro feature because of this.

**Comment by kunalmkamble** [comment]
changed back 
import { HotTableModule } from 'angular-handsontable';
from 
import { HotTableModule } from 'angular-handsontable/index';

Cleaned npm cache, and installed handsontable module again. 
This fixed above isssue mentioned.

**Comment by kunalmkamble** [comment]
With below line to include HotTableModule pro features stopped working for me.
import { HotTableModule } from 'angular-handsontable/index';

if I changed it to 
import { HotTableModule } from 'angular-handsontable/index';
Below error starts showing up in the browser console. 
> No provider for HotRegisterer!

**Comment by AMBudnik** [comment]
Hi @kunalmkamble 

Have you added the `HotTableModule` into `imports` as shown below (_app.module.ts_)?

```
  imports: [
    BrowserModule,
    HotTableModule
  ],
```

**Comment by kunalmkamble** [comment]
Yes, i did.

**Comment by AMBudnik** [comment]
Can you share your app.component.ts file?

**Comment by kunalmkamble** [comment]
Our app structured  like App module has core module . Core module is making use of handsontable. So sharing our core module and component files. 

[Archive.zip](https://github.com/handsontable/angular-handsontable/files/1339827/Archive.zip)

**Comment by kunalmkamble** [comment]
Yes, you are correct. If use it as above mentioned I end up getting 
`No provider for HotRegisterer!`
in the browser console, and handsontable wont render.

**Comment by AMBudnik** [comment]
@swistach do you have any ideas what can cause this issue?

**Comment by GregFuntera** [comment]
in app.module.ts  @NgModule add below 
providers:[HotRegisterer]
It somehow fixed my problem for my error No provider for HotRegisterer!

**Comment by kunalmkamble** [comment]
Thanks @GregFuntera that solved my problem too!

**Comment by GregFuntera** [comment]
Have you tried adding  a hotId in **component.html**
**<hot-table>hotId="hotInstance" </hot-table>**
then in your **component.ts**
export class AppComponent {
   instance: string = "hotInstance";
   constructor(private _hotRegisterer: HotRegisterer) {}
   private doSomething() {
        const hot = this._hotRegisterer.getInstance(this.instance);
   }
}

**Comment by kunalmkamble** [comment]
Yes,  i I already have mentioned setting in component.html . No success.

**Comment by swistach** [comment]
Hi @kunalmkamble 
Here is a simple demo: https://stackblitz.com/edit/angular-handsontable-hotregisterer?file=app%2Fapp.component.ts
