### ISSUE TITLE
 Doc - Adding save Data to Bind Handsontable to a remote data Example

### ISSUE THREAD

**Issue by yehia2amer** [handsontable/angular-handsontable#25]
### Description

In the [Bind Handsontable to a remote data source](https://handsontable.github.io/angular-handsontable/examples/remote-data) page , It will be great to add Saving data in addition to Loading , so that it matches [Handsontable Load and save tutorial ](https://docs.handsontable.com/0.34.4/tutorial-load-and-save.html)

**Comment by AMBudnik** [comment]
Thank you for sharing your suggestion.

**Comment by MateuszG** [comment]
Here is my proposition:
https://stackblitz.com/edit/handsontable-angular-remote-data-2i8t3k?file=app%2Fapp.component.ts

**Comment by swistach** [comment]
The example is changed.
