### ISSUE TITLE
HOT-component emits afterChange event on initiation

### ISSUE THREAD

**Issue by ottosson** [handsontable/angular-handsontable#26]
### Description

I have an afterChange event to catch changes in my table. But when the component is initialized the event is fired as a more or less empty event:
```
<hot-table
  (afterChange)="postChange($event)"
  hotId="hotInstance">
</hot-table>

...

postChange(event) {
  console.log(event);  // [null, "loadData", undefined, undefined, undefined, undefined]
}
```

Is this expected behavior?

### Your environment
* Wrapper version: 1.0.0-beta2

**Comment by AMBudnik** [comment]
Hi @ottosson 

`afterChange` on the initialization informs about the fact that data has been loaded via `loadData` string representative with an empty array of changes. It is an intended behavior.

**Comment by ottosson** [comment]
@AMBudnik Ok! Thanks for clearing that up for me! =)
