### ISSUE TITLE
Routerlink attribute not working in custom cell

### ISSUE THREAD

**Issue by kunalmkamble** [handsontable/angular-handsontable#27]
### Description
Routerlink not working in custom cell

### Steps to reproduce
I am trying to setup  "routerLink"  attribute for the HTML generated for one of the cell for custom renderer has been added. Event is not getting fired when element is clicked on the UI element. Is there is work around to this?

### Your environment
* Latest chrome
* Mac OS

**Comment by kunalmkamble** [comment]
### Context 
We are implementing File upload feature. Here user can click to a cell which is custom rendered to upload a file. So when user clicks on this custom rendered cell we would like to navigate to the route which handles the file operation,  with relevant parameter fetched from  row data.

**Comment by swistach** [comment]
Hi @kunalmkamble 
I suppose it's related to #22.
On the one hand we init Handsontable in `runOutsideAngular` what is fine to keep enough good performance level, on the other hand probably is a reason why angular components doesn't work in `hot-table`.
Please track #22 issue for any updates.

**Comment by SarfaleSiddharth** [comment]
Hello @swistach 
Is there any way to write routerLink in table cell?

I tried write routerlink directly and used html renderer, but it's not working.

**Comment by AMBudnik** [comment]
Hey @SarfaleSiddharth 

that's a feature request that is currently on hold.

**Comment by SarfaleSiddharth** [comment]
Hello @AMBudnik 
Thanks for the update
Any idea, when we can have this feature active? or any other alternative workaround for this?

**Comment by AMBudnik** [comment]
We are currently focusing on adding new formulas to Handsontable so it's really hard to tell. I will make sure to update you once we get this done.
