### ISSUE TITLE
How to add copyPasteContextMenu for the angular 2 wrapper

### ISSUE THREAD

**Issue by GregFuntera** [handsontable/angular-handsontable#28]
How do you properly add the copypaste in context menu for the wrapper.
As seen in this example: http://jsfiddle.net/api/post/library/pure/

**Comment by swistach** [comment]
Hi @GregFuntera, here is an example: https://stackblitz.com/edit/angular-handsontable-issue-28

**Comment by swistach** [comment]
We can close this issue if there is nothing more to add.
