### ISSUE TITLE
Formulas not working properly in PRO edition

### ISSUE THREAD

**Issue by GregFuntera** [handsontable/angular-handsontable#29]
Hi, 
I'm having some issues with the formulas in the wrapper only the **SUM** formula is working properly but for the formulas **AVERAGE,COUNT,MAX,MIN**  is not working properly.

BTW I have an event function for enter key.

Thank you.

**Comment by AMBudnik** [comment]
Hi @GregFuntera 

the Formula Support plugin is in alpha stage. I think that the issue may not be related to the Angular wrapper. Can you share a demo (JSFiddle/JSBin/CodePen) with a bug scenario?

**Comment by swistach** [comment]
Without an example, we cannot help you.
Reopen this issue if you will prepare a demo.
