### ISSUE TITLE
ES2016 feature may break build

### ISSUE THREAD

**Issue by jornare** [handsontable/angular-handsontable#3]
https://github.com/handsontable/angular-handsontable/blob/2de1c0c1f4eef1fadc6e4848431d013b35698595/src/hot-settings.utils.ts#L66

Using [].includes(key) may break a build yielding
`TS2339: Property 'includes' does not exist on type 'string[]'.`
Consider using [].indexOf(key) > 0 for compatibility.

**Comment by swistach** [comment]
Hi @jornare,
I agree with you. Before beta release, it will be changed.
But in the meantime, you can add "es2016" into `lib` array in `tsconfig.json` file.

**Comment by jornare** [comment]
Alternatively, please document well that one may add this functionality in tsconfig.json

```
    "lib": [
      "dom",
      "es6",
      "es2016.array.include"
    ],
```

**Comment by swistach** [comment]
Currently it could stay as `AVAILABLE_HOOKS.indexOf(key) > -1`.
Thank you for your help :+1:
