### ISSUE TITLE
filter on handsontable-pro

### ISSUE THREAD

**Issue by brynnlow** [handsontable/angular-handsontable#30]
Hello,
I want to try Handsontable for a project, but I'm facing some problem
I can not access the PRO function

I try to put an example on plunker but I do not know how to run Handsontable before zone.js
here is the link : https://plnkr.co/edit/WnQ5NoxrfpwLpX2ihh70 (may be that you know how to do that)

so I will explain with a minimal example

If i add `import 'handsontable';` in the polyfills.ts i have the promise error, if i add `import 'angular-handsontable';` i have always the promise error, I have to add both so that the error disappears.

in my tsconfig.json i have added in compilerOptions
`"paths": {
      "handsontable": ["../node_modules/handsontable-pro/dist/handsontable.full.js"]
    }`

in my style.scss i use
`@import '~handsontable-pro/dist/handsontable.full.min.css';`

and in my app.component.ts i have
`import { Component } from '@angular/core';
import Handsontable from 'handsontable';
@Component({
  selector: 'app-root',
  template: `<hot-table [settings]="settings"></hot-table>`,
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app';
  settings = {
    data: Handsontable.helper.createSpreadsheetData(5, 5),
    colHeaders: true,
    dropdownMenu: true,
    filters: true,
    contextMenu: true,
    multiSelect: false,
    disableVisualSelection: ['current', 'area'],
    currentRowClassName: 'currentRow'
  };

  constructor() {
    console.log(`Handsontable version: ${Handsontable.version}`);
  }
}`

the console log seem fine: Handsontable version: 1.14.2
but this is my result
![filter-handsontable](https://user-images.githubusercontent.com/16014174/31219563-03b8faf2-a9be-11e7-8018-4d7984e221c0.png)

i have no filter
i have try to inverse the import in the polyfill.ts, import real data, change the options, or delete the handsontable package for let only the handsontable-pro but this change nothing

for info i use angular 4.2.4

**Comment by AMBudnik** [comment]
Hi @brynnlow 

as far as I know, it's currently impossible technically to get the pro working with the angular wrapper 

The change for the `polyfills.ts` file is only adding the

**Comment by brynnlow** [comment]
thank you for you quick reply,
my package.json seems good
`"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-handsontable": "^1.0.0-beta3",
    "core-js": "^2.4.1",
    "handsontable-pro": "^1.14.2",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  }`

my tsconfig seems good too
`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "handsontable": ["../node_modules/handsontable-pro/dist/handsontable.full.js"]
    }
  }
}`

just my pollyfill.ts is different

`import 'handsontable';
import 'angular-handsontable';

 /***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.`

if i import just one of these, i have an error
`import 'handsontable';
// import 'angular-handsontable';

/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.`

> Uncaught TypeError: NativePromise.resolve is not a function
    at Object.setNativePromise (zone.js:634)
    at desc.set (zone.js:1028)
    at module.exports (index.umd.js:23472)
    at $export (index.umd.js:19423)
    at Object.<anonymous> (index.umd.js:32227)
    at __webpack_require__ (index.umd.js:17700)
    at Object.<anonymous> (index.umd.js:43285)
    at __webpack_require__ (index.umd.js:17700)
    at exports.__esModule (index.umd.js:17743)
    at index.umd.js:17746

**Comment by AMBudnik** [comment]
Maybe this will help.

I am attaching a simple PRO integration (without the `node_modules` folder and the `licenseKey`)
[my-app.zip](https://github.com/handsontable/angular-handsontable/files/1359393/my-app.zip)

before you call the server add the `node_modules`

**Comment by brynnlow** [comment]
thank you very much, i found my problem
in the documentation you have 
`import { HotTableModule } from 'angular-handsontable';`

but in your exemple it is 

`import {HotTableModule} from 'angular-handsontable/index';`

change this solve my problem, may be refresh the doc ?

**Comment by AMBudnik** [comment]
Oh yes, that's a workaround to use the `/index`. It should be available at `angular-handsontable`. It's marked as something to be fixed.

ps. thanks for an update :) I am glad that it works now.

**Comment by brynnlow** [comment]
Hi,
Thanks for your help. So far I think pro functionalities are working fine.

I have one last question :
On your first comment you told me "as far as I know, it's currently impossible technically to get the pro working with the angular wrapper". Is it still the case or not  ?  What are the current limitation of using handontable with then angular 2 wrapper ?

Best regards

**Comment by AMBudnik** [comment]
@brynnlow sorry for the misunderstanding. I was thinking about making them work in Plunker.

**Comment by galuszkak** [comment]
@AMBudnik I tried Your example, it works fine, but if You upgrade to Angular 5 it doesn't display any filters at all. In fact it looks like this is lacking dropdown menu then. Do you know what causes it and when it will be fixed? We use PRO version of handsontable and for now it's unable to run PRO version features like this one dropdown menu:
<img width="469" alt="screen shot 2017-11-21 at 7 29 46 am" src="https://user-images.githubusercontent.com/759579/33053847-42bcf622-ce8f-11e7-90b4-a7ebe61825ee.png">

Here is code of Your example updated (ZIP file):
https://drive.google.com/file/d/1_K61MKh76A6TEb424Wz1zGmapLeXVByJ/view

**Comment by AMBudnik** [comment]
We did not test the wrapper more closely with Angular 4 and had no time for Angular 5. However, it looks like the PRO hasn't been activated.
@galuszkak can you check if any other PRO features are unavailable?

**Comment by galuszkak** [comment]
@AMBudnik we have large code base where it's activated license. So for example, hidding columns works, but filters/dropdown menu don't.

**Comment by AMBudnik** [comment]
Thank you for checking that @galuszkak It's a very important information.
@swistach this can be more complicated with Angular 5. We need to check that soon.

**Comment by galuszkak** [comment]
@AMBudnik appreciate any help on that, if You need any another example apps like showed before I can provide those.

**Comment by AMBudnik** [comment]
Thank you for your effort and time to investigate this case. I think that @swistach will post any requests when needed. Currently, he's finishing some [fixes for the vanilla version](https://github.com/handsontable/handsontable/issues/4536)

**Comment by galuszkak** [comment]
@AMBudnik any progress on that issue?

**Comment by AMBudnik** [comment]
Sorry, but this can take a little bit longer. The vanilla version bugs have higher priority than the wrapper. However, I was told that the next stage of fixes in Angular wrapper should start in December.

**Comment by eriksteinebach** [comment]
I have been testing this today. I couldn't get it to work, it looked like the pro version wasn't enabled. The /index solution mentioned also didn't work for me because it gave the error:
```
ERROR in ./node_modules/angular-handsontable/index.ts
Module build failed: Error: C:\...\node_modules\angular-handsontable\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\....\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:648:23)
    at plugin.done.then (C:\...\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 39:0-60
```
It only worked when I downgraded Angular 5.0.0 to 4.2.4 (the same version as in the zip supplied). 

Can I conclude from this that handsometable-pro doesn't work with Angular 5?

**Comment by swistach** [comment]
Hi @eriksteinebach 
Unfortunately, in Angular 5, our workaround for adding a custom `paths` option:
```
"handsontable": ["../node_modules/handsontable-pro/dist/handsontable.js"]
```
doesn't work anymore.
Probably, `angular` configuration was changed and now `*.js` files are ignored.

I'm working on a solution to make possible use `Handsontable Pro` in the wrapper.

**Comment by eriksteinebach** [comment]
@swistach Thank you. I saw in the roadmap the Angular wrapper is being worked on at the moment? Is this part of that work? And do you have an indication when this should be out there? Days, Weeks or Months? No need for specifics, just an indication of scope/timeframe is fine, so I can make plans for our business

**Comment by swistach** [comment]
Yes, it's part of that work.
Currently, I'm working on adjustment my implementation with use of [dherges/ng-packagr](https://github.com/dherges/ng-packagr) pattern.
I suppose that during next week should be done new prototype with  `peerDependencies` instead of `dependencies` and with separate subdirectories for ce and pro:
`import { HotTableModule } from 'angular-handsontable/ce';`
`import { HotTableModule } from 'angular-handsontable/pro';`

**Comment by eriksteinebach** [comment]
That sounds great! Let me know if I can help test something.

**Comment by tate-bowman** [comment]
Thanks guys, I’m also willing to test if needed.

**Comment by brynnlow** [comment]
can we have an approximate date for a pro version compatible with angular5?

a test version is welcome

**Comment by AMBudnik** [comment]
Hi @brynnlow 
The stable version (1.0.0.) that will support @angular/core@5.0.0 is planned for this week.

**Comment by brynnlow** [comment]
thanks you Aleksandra

**Comment by anandhuajayakumar** [comment]
Hi @AMBudnik , 
has the stable version for 5.0.0 been released.

**Comment by swistach** [comment]
Hi @eriksteinebach and @tate-bowman,
If you still would like to test the new version, you can use `@handsontable/angular` or `@handsontable-pro/angular`.

Is still as the beta, because of incompatibility with angular 4. Fortunately, I have an idea how to resolve this problem.

So, here is a short instruction, how to use it:
1. `npm install -g @angular/cli`
2. `ng new ng-app && cd ng-app && npm i -D @handsontable-pro/angular handsontable-pro && npm start`
3. In `src/app/app.module.ts` file, you have to add `import { HotTableModule } from '@handsontable-pro/angular';` after rest of imports. Then you can add `HotTableModule.forRoot()` in `imports` array in module.
4. In `src/style.css` you have to add `@import '~handsontable-pro/dist/handsontable.full.css'`.
5. In `src/app/app.component.html` file you can replace content with `<hot-table></hot-table>`.
6. Open `http://localhost:4200` in your browser.

Here is an online example: https://stackblitz.com/edit/angular-handsontable-pro?file=app%2Fapp.module.ts
