### ISSUE TITLE
Custom editor register / DateTimeEditor

### ISSUE THREAD

**Issue by dnaprawa** [handsontable/angular-handsontable#31]
Hello,

I am using angular-handsontable with angular 4.

My question is how to register custom editor ? I didn't find anything about it in documentation. I want to register custom DateTimeEditor to make DateTime cell.

Or if there is another way to make a DateTime cell with DateTime picker I would be grateful for that solution.

**Comment by swistach** [comment]
Hi @dnaprawa,
Here is a simple demo: https://stackblitz.com/edit/angular-handsontable-custom-editor?file=app%2Fapp.component.ts

**Comment by swistach** [comment]
I think we solved this issue. Feel free to reopen this issue if you find problems with custom editors.
