### ISSUE TITLE
Angular breaks the ability to select all hidden columns

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/angular-handsontable#33]
### Description

As reported at https://forum.handsontable.com/t/show-hide-copy-inconsistent/1565
It's an Angular only bug. It does not occur for the vanilla version.
> I am using PRO 1.14.2 with Angular4.
> 
> I am loading data for grid on init, and hide/show cols based on condition.
> 
> Say, table has a,b,c,d as columns. Once initialized with data, I am updating through settings to hide c,d based on user selection. It is hiding the columns. But when I copy the grid through Ctrl+C, only a,b are copied.
> If I hide just column c, then on copy it is copying all the columns (including hidden).
> 
> Looks like if hidden columns are at the end, they are not copied.If they are in between they are copied.
> 
> Please clarify on this. 
> This fiddle I tired with end columns, it is working, but not in Angular Wrapper http://jsfiddle.net/6y8f4xrL/

### Steps to reproduce

1. Hide any column on the beginning or at the end of the table
2. Click <kbd>CTRL/CMD</kbd> + <kbd>A</kbd> to select all columns
3. Use any other editor - can be Excel/Calc as well to paste the values

### Your environment
* Wrapper version: 1.0.0-beta3
* Browser Name and version: Chrome 62
* Operating System: Windows 10

**Comment by sumavr** [comment]
Any updates on this?

**Comment by AMBudnik** [comment]
No updates yet @sumavr 
@swistach has just started to update the wrapper. The issue will be tested but there's no deadline for it to get fixed.

**Comment by swistach** [comment]
I think we can close this issue. Feel free to reopen this one if you find similar problems in the most recent version.

**Comment by sumavr** [comment]
Updated the version to     
"@handsontable-pro/angular": "^1.0.0-beta4",
    "handsontable-pro": "^1.15.1",

issue still remains...

**Comment by swistach** [comment]
Hi @sumavr, 
as I mentioned before, this behaviour is exactly as we expect. There is no issue in my opinion. Especially in the wrapper.

If you think, that selection all cells and hiding columns/rows should work in a different way, you can create new issue [here](https://github.com/handsontable/handsontable-pro/issues/new).
I would like to notice that is the same behaviour like in Google Sheets.
