### ISSUE TITLE
Customizing drop down for a column ?

### ISSUE THREAD

**Issue by pmajhwar** [handsontable/angular-handsontable#35]
Hi, I was trying to customize dropdown available for a column.
Right now this supports only array of strings.
Is it possible to bind JSON data having id and name.  how do i specify name as the display value.
Please help.

Kind regards

**Comment by AMBudnik** [comment]
I think that I have an example that may help http://jsfiddle.net/handsoncode/kzfjf179/

**Comment by pmajhwar** [comment]
Thank you so much @AMBudnik. This is helpful.
I am looking for further customization i.e. expand collapse groups of choices, something like this--> http://jsfiddle.net/1aeur58f/867/.  If i click on microphone or video sources list expands.

I tried writing customeditor but the collapse expand isn't working. 
I created a repo for the same here.. https://github.com/pmajhwar/ht-pro-custom-editor.

Can you please help!

Kind regards

**Comment by AMBudnik** [comment]
Hi @pmajhwar maybe it would be easier to use Bootstrap tabs and place the table on the shown tab?
I have something like this here http://jsfiddle.net/ygwepsqg/ (but the menu in horizontally aligned)

**Comment by pmajhwar** [comment]
Hi @AMBudnik 
am afraid tabs won't help, we want cell editor customization. wherein when a cell is edited it shows up our custom editor. Kind of editor needed is posted in previous chat.
Please advise.

kind regards,

**Comment by AMBudnik** [comment]
If you would like to get a similar result using only the table you can use [nestedRows ](https://docs.handsontable.com/pro/demo-nested-rows.html)feature (Handsontable PRO). Here is a working example http://jsfiddle.net/handsoncode/zkv6n0ah/

**Comment by swistach** [comment]
I suppose that `nestedRows` is the best solution for you. Feel free to leave a comment if you would like to add something.

**Comment by ChandraAdapa10** [comment]
HI AmBudnik,

can we have bootstrap or mat dropdown in handsontable column(some thing like this https://codepen.io/rustybailey/pen/GJjvYB).
if you have any working example , please share it

Thanks,
Chandra

**Comment by AMBudnik** [comment]
Hi @ChandraAdapa10 please join me on emails - support@handsontable.com This topic is 2018 and possibly won't be opened.
Generally, the following functionality can be achieved with use of or a custom editor and renderer. But, we do not have an exact example like this in our demo base.

**Comment by ChandraAdapa10** [comment]
Hi AMBudnik,

Yes I have tried editor and renderer,  but its not working.
I can send an email for the same.

Thanks,
chandra

**Comment by AMBudnik** [comment]
> I can send an email for the same.

Great. Thank you.
