### ISSUE TITLE
Customizing Header context menu

### ISSUE THREAD

**Issue by pmajhwar** [handsontable/angular-handsontable#36]
Hi, I was trying to customize context menu available in column header. Is it possible to enable context menu or drop down menu for only 1 column header and disable for other column headers ?

Is it possible to move sorting from my customized header menu and provide multi-select drop down with check-boxes in it ?
Please help.
Kind regards

**Comment by AMBudnik** [comment]
Hi @pmajhwar 

I can an example for a custom context menu in vanilla version but you shouldn't have any problems doing the same in Angular version http://jsfiddle.net/handsoncode/1pfu1u62/ If you do not want to show a function in some column just use the `disabled` key and pass the column index.

When it comes to sorting you can turn it off via its plugin -> `columnSorting: false` and to add a custom header you can use the [`afterGetColHeader`](https://docs.handsontable.com/pro/1.14.3/Hooks.html#event:afterGetColHeader) method.

**Comment by swistach** [comment]
@pmajhwar: I suppose that you resolved this issue. If not, feel free to reopen it.
