### ISSUE TITLE
Provision to add progress bar on paste

### ISSUE THREAD

**Issue by sumavr** [handsontable/angular-handsontable#37]
### Description
When large data is pasted, the grid freezes, until the data cells are written with data. However user remains puzzled what is happening. It would be good if the progress bar integrated with hot-table to bind this ;beforePaste and afterChange (CopyPaste.Paste) events

### Steps to reproduce
1. Paste large data on hot-table

### Your environment
* Wrapper version: "angular-handsontable": "^1.0.0-beta2", "handsontable-pro": "^1.14.2",
* Browser Name and version: Chrome 62
* Operating System:

**Comment by AMBudnik** [comment]
Topic already opened at https://forum.handsontable.com/t/which-is-the-best-place-to-bind-progress-bar-invocation-during-paste/1585/2
