### ISSUE TITLE
Custom Editor using Angular 4 -  Handsontable.editors.BaseEditor.prototype- prototype not defined

### ISSUE THREAD

**Issue by pmajhwar** [handsontable/angular-handsontable#38]
I wanted to build custom editor "SelectEditor - creating editor from scratch"  for my cells and was trying the basics from the following reference URL...
https://docs.handsontable.com/pro/1.14.3/tutorial-cell-editor.html#page-inheritance-of-editors

But got stuck at the first step where Handsontable.editors.BaseEditor.prototype is not available for me to proceed. 
Do we have an alternate example in Angular 4, this would be extremely helpful.
Please help, a little urgent.

Kind regards

**Comment by swistach** [comment]
Hi @pmajhwar,
here is a simple demo: https://stackblitz.com/edit/angular-handsontable-custom-editor?file=app%2Fapp.component.ts
In the example, I used Angular 5, but it's the same rule to create a custom editor.

**Comment by ivorobioff** [comment]
This could be unrelated question but how do I get a root element within that class?
