### ISSUE TITLE
get data after modifying

### ISSUE THREAD

**Issue by newmesiss** [handsontable/angular-handsontable#39]
from my controller I define my parameter data with zero parameters, then I am adding data to taste in my view, when I want to save in my database it does not take the modified data in my view
```
   this.data = [{rut: 0 , valor: 0}];
```

      <hot-table 
      height="300" 
      [settings]="settings" 
      [columns]="columns" 
      [data]="data"
      ></hot-table>

```
  updateImport(datahot){
    this.importacionService.updateImport(this.data); //data is Undefined 
  }
```

in my view everything is fine just that the modified or added is not updated in my this.data

**Comment by swistach** [comment]
Hi @newmesiss,
Below is a simple example how to bind changes between the Handsontable and parent component.
https://stackblitz.com/edit/angular-handsontable-issue-39?file=app/app.component.html

**Comment by doczoidberg** [comment]
this does not work any more

**Comment by AMBudnik** [comment]
Hey @doczoidberg 

Please share a bug scenario that you've encountered.
