### ISSUE TITLE
Only works in Chrome

### ISSUE THREAD

**Issue by eitland** [handsontable/angular-handsontable#4]
When opening a page that uses handsontable wrapper in Edge, Firefox or Chrome it seems to work until you try to edit. 

In Chrome I can select cells, edit the content etc. In other browsers nothing happens.

In the developer console I get this message:

`ReferenceError: Core is not defined[Learn More] polyfills.bundle.js:7245:1`

It fails both in my application as well as in your documentation app from the branch gh-pages.

**Comment by swistach** [comment]
You're absolutely right. This issue must be resolved immediately.
Thank you very much @eitland!

**Comment by swistach** [comment]
Related issue: handsontable/handsontable#4494

**Comment by swistach** [comment]
This issue is fixed in Handsontable 0.34.1
