### ISSUE TITLE
Cannot call a function in the parent component

### ISSUE THREAD

**Issue by david-j-lee** [handsontable/angular-handsontable#40]
I have a component, MainComponent, that has a hot-table with a function to handle deleting a row. I then have a button rendered on each row on a html column within Handsontable with the attribute `(click)="delete(id)"`. When the table renders and I click on the button the delete function never gets hit. From what I can tell the hot-table creates a new component within my MainComponent. As a result my button has no idea what my delete function is as the button is on the Handsontable Component and the function is on my MainComponent. Is there a way to allow methods to be inserted into the Handsontable component or am I missing something that should allow me to do this? Thanks in advance!

**Comment by david-j-lee** [comment]
I just ended up using the afterOnCellMouseDown and checked for the correct column before deleting. Not the cleanest work around, but it works.

**Comment by AMBudnik** [comment]
That's a quick update. I am happy to hear that you've found a solution. 
I can check your demo if you have one but as you have already found a code that works (and doesn't sound as dirty as you think) I would stick with that.
