### ISSUE TITLE
CSS incompatibility with material2

### ISSUE THREAD

**Issue by pankaj28843** [handsontable/angular-handsontable#43]
### Description
When I use <hot-table> inside a [material2 component](https://material.angular.io/components/categories) e.g. mat-stepper, then table does not behave as expected, e.g. column headers don't scroll along with data rows when overflow happens.

### Steps to reproduce
Code - https://stackblitz.com/edit/angular-handsontable-material-issue?file=app%2Fapp.component.html

### Demo
Demo App - https://angular-handsontable-material-issue.stackblitz.io/

### Your environment
* Wrapper version: 1.0.0-beta3
* Browser Name and version: Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)
* Operating System: Ubuntu 17.10

**Comment by AMBudnik** [comment]
Hi @pankaj28843 

have you tried to attach a Handsontable to a parent wrapper container?

**Comment by pankaj28843** [comment]
@AMBudnik Thanks for the reply.

I have tried following:

In the template:
```html
<div #tpl></div>
```
In the component:
```ts
  @ViewChild('tpl') tpl: TemplateRef<any>;

  ngAfterViewInit() {
    const options = Object.assign({}, this.settings);
    const hotInstance = new Handsontable(this.tpl.nativeElement, options);
  }
```

But I saw same issue as before.

It does not seem like an issue with angular-handsontable. but material2 and handsontable css.

Do you have any more suggestions?

**Comment by AMBudnik** [comment]
You can check if any styles from material are overwriting handsontable.css
I found the Chrome's dev tools to do it the best

**Comment by pankaj28843** [comment]
@AMBudnik I checked the computed styles using the Chrome Dev Tools. But I could not find any difference between two instances.

However, as I scroll horizontally, left position of `<div class="wtSpreader">` gets updated if `<hot-table>` is outside the material stepper. Otherwise, it does not get updated.

I am not able to figure out why this would break. Can it be because Material is stopping event propagation of scroll event?

**Comment by AMBudnik** [comment]
I think that this issue can take a little longer to investigate. I'll add a 'bug' label

**Comment by swistach** [comment]
Hi @pankaj28843,
@AMBudnik is right.
This is a bug in the `vanilla` version: http://jsfiddle.net/a6447rug/

**Comment by pankaj28843** [comment]
Hi @swistach,
Thank you for confirming that it is a bug.
So, does it not have anything to do with Material 2?

**Comment by swistach** [comment]
You can try to run `updateSettings({})` if mat-stepper emit event after init and/or change. But you have to be sure that it is ready and registered `hot-table` component.

Modified `vanilla` example: http://jsfiddle.net/Leszpbq8/
But in the angular component, I think that could be necessary to add force rerender in the `ngAfterViewChecked` hook.

**Comment by swistach** [comment]
I close this issue. You can follow progress in handsontable/handsontable#5633.
Feel free to reopen if workaround doesn't help.

Thank you @pankaj28843 for your help :+1:
