### ISSUE TITLE
Dropdown selects first option without selecting anything.

### ISSUE THREAD

**Issue by kunalkakkad** [handsontable/angular-handsontable#44]
Hello,

For column type:dropdown, when user click on dropdown ,doesn't selects any option and click anywhere else then the dropdown is selected with the first option by default.

Expected behavior: It should select any option when we click on option otherwise it should not select.

Actual behavior: It is selecting first option by default which actually it should not.

Any assistance is highly appreciated.

Thanks & Regards,
Kunal Kakkad

**Comment by AMBudnik** [comment]
Hi @kunalkakkad 

dropdown by default should not change anything when a user just opens the list and close it (like you rightly pointed). The proper behavior can be replicated by our main dropdown demo at https://docs.handsontable.com/pro/1.15.0/demo-dropdown.html

![gif](https://user-images.githubusercontent.com/10757813/34513511-e32bbc92-f068-11e7-802c-cc136e0d1954.gif)

Do you get any other result?

**Comment by kunalkakkad** [comment]
@AMBudnik When either there is nothing selected initially or else if we remove the selected thing and make it blank and then focus to some other cell.

**Comment by AMBudnik** [comment]
You are right, we are not able to delete the content while editing and leave it blank after editor gets closed. We can only use <kbd>DEL</kbd> key on a selected cell.
I have replicated in on the vanilla version so reported it at https://github.com/handsontable/handsontable/issues/4703. Please try updates to this issue for further information.

**Comment by swistach** [comment]
Hi @kunalkakkad,
you can subscribe handsontable/handsontable#4703 to be up to date with the information related to this issue.
