### ISSUE TITLE
HotRegisterer is undefined in [cells] properties renderer method

### ISSUE THREAD

**Issue by amit-metkar** [handsontable/angular-handsontable#47]
### Description
I'm trying to have custom logic while binding cells, and I want to use HotRegisterer to get an instance of handsontable. [docs](https://handsontable.github.io/angular-handsontable/examples/access-to-handsontable)  
`const hot = this.hotRegisterer.getInstance(this.instance);`

getting an error on above line,
> **ERROR TypeError: Cannot read property 'getInstance' of undefined**

Please help me to resolve this issue!!!

I have imported HotRegisterer my angular component. 
`import { HotRegisterer } from 'angular-handsontable';`

polyfills.ts [from issue reference](https://github.com/handsontable/handsontable/issues/4495#issuecomment-329110036) 
```
import 'angular-handsontable'; 
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

template
```
<hot-table #ht [hotId]="instance" [settings]="settings" [fixedRowsTop]="fixedRowsTop" [fixedColumnsLeft]="fixedColumnsLeft" [mergeCells]="mergeCells" [cells]="cells"
      [data]="data" (afterSelection)="onAfterselection($event, ht)"></hot-table>
```

component 
```
// other imports
import { HotRegisterer } from 'angular-handsontable';

// other code 
constructor(
    private http: Http,
    private route: ActivatedRoute,
    private hotRegisterer: HotRegisterer) {
}

// other code
cells(row, col, prop) {
    const cellProperties = {};
    const hot = this.hotRegisterer.getInstance(this.instance);
    if (this.metaData &&
      this.metaData['requested_variables'].indexOf(hot.getDataAtCell(row, 0)) !== -1) {
      if (col > 2) {
        cellProperties['renderer'] = this.cellsRenderer_1.bind(this); 
      } else {
        cellProperties['readOnly'] = true;
      }
    } else {
      cellProperties['renderer'] = this.cellsRenderer_2.bind(this);
      cellProperties['readOnly'] = true;
    }
    return cellProperties;
  }
```

### Steps to reproduce
`const hot = this.hotRegisterer.getInstance(this.instance);`

getting an error on above line,
> ERROR TypeError: Cannot read property 'getInstance' of undefined

### Your environment
   ```
 "@angular/animations": "^4.1.2",
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/core": "^4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "4.1.2",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@angular/router": "4.1.2",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.5",
    "@angular/cli": "1.5.4",
    "@angular/compiler-cli": "4.1.2",
    "@angular/language-service": "4.1.0",
```
* Wrapper version: 
```
    "angular-handsontable": "^1.0.0-beta3",
    "handsontable@0.34.4"
```
* Browser Name and version: Chrome v57
* Operating System: Windows7

**Comment by swistach** [comment]
Hi @amit-metkar,
In your case `this` is a reference to `ColumnSettings`, that means you can get an access to instance of the Handsontable without `hotRegisterer`.
Example: https://stackblitz.com/edit/angular-handsontable-rjc9zn?file=app%2Fapp.component.ts

**Comment by amit-metkar** [comment]
Thank you so much @swistach for answering my query!
I have tried that, but I need this object which is an instance of component, so I had modified my template as below,
```
<hot-table #ht [hotId]="instance" [settings]="settings" [fixedRowsTop]="fixedRowsTop" [fixedColumnsLeft]="fixedColumnsLeft" [mergeCells]="mergeCells" [cells]="cells.bind(this)"
      [data]="data" (afterSelection)="onAfterselection($event, ht)"></hot-table>
```

It is weird that, I am getting HotRegisterer instance as undefined in some cases and in some as HotRegisterer object type (not sure what are specific cases). so my 1 problem is resolved by just adding if condition on usage, like follows,

```
cells(row, col, prop) {
    const cellProperties = {};
    const hot = this.hotRegisterer.getInstance(this.instance);
    if (hot) {
        // code
    }
    return cellProperties;
  }
```

But it has produced another issue OR might be there all the time but seen now, 
I'm using [height] & [width], [fixedRowsTop] & [fixedColumnsLeft] binding on hot-table directive, to have scrolls when large data is bound with some data frozen, I get the V & H scrolls now, but **when I scroll right, at the end, grid structure gets distorted!!**

I haven't created another issue for this because, it looks related to [cells] binding on hot-table directive!
Everything works perfectly, if I don't bind [cells] to hot-table directive. 

I see, [cells] is getting called on every mouse movement. and something happens when I scroll to extreme right of available scroll width. And it is practically impossible to debug it, as [cells] gets called on every mouse movement for all cells in table/sheet.

Unfortunately, I can not give you screen shot because of corporate policy!

Appreciate your help on this!

Thanks :)

**Comment by swistach** [comment]
Could you make a simple demo, only with necessary options, based on my example?
It will be helpful for me :wink:

**Comment by amit-metkar** [comment]
Sure, I understand, let me work on demo, and find out way to share it from our restricted environment.

**Comment by amit-metkar** [comment]
Hi @swistach,

Please find demo on https://stackblitz.com/edit/angular-handsontable-demo?file=app%2Fapp.component.html

I have commented and kept few cases  in html file, that I found, might be helpful to you for troubleshooting. Please try few times to break it, after clearing cache.

 Please let me know if you need any help from me.

**Comment by amit-metkar** [comment]
Hi @swistach,
I have updated demo, added some content at the top of the hot-table. 
I have observed, issue is reproducible, if hot-table has some content at top which pushes hot-table near bottom of the page. it depends on how much space/resolution you have on your screen, if you have bigger screen, then update demo to push hot-table near bottom of the page.

https://stackblitz.com/edit/angular-handsontable-demo?file=app%2Fapp.component.html

Thanks,
Amit

**Comment by swistach** [comment]
Ok, the scrolling issue is another problem, related to Handsontable handsontable/handsontable#3618.

So, let's back to the point. Your major question is:
How to use both of references, to the Handsontable and to the component, in `cells` property. 
Here is a simple example, how you can solve this problem: https://stackblitz.com/edit/angular-handsontable-rjc9zn-4ppfhg?file=app/app.component.ts

**Comment by swistach** [comment]
We can close this issue if there is nothing more to add.
