### ISSUE TITLE
angular-handsontable@1.0.0

### ISSUE THREAD

**Issue by swistach** [handsontable/angular-handsontable#48]
### Description
Currently, I'm working on new, [AFPv5](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.k0mh3o8u5hx) compatible wrapper.

The new version requires `zone.js@0.8.19` and higher.

To-Do list:
- [x] wrapper for CE version should be available by `import {...} from 'angular-handsontable'`
- [x] wrapper for PRO version should be available by `import {...} from 'angular-handsontable/pro'`
- [x] tests
- [x] should works properly with `ng build --prod`
- [x] should works properly with `ng build --prod --aot`
- [x] should be possible to use the wrapper in dev environment `ng serve`
- [x] npm package should be free from unnecessary files (src, tests)

If you have any idea, what else I should add to the wrapper, share it in a comment.

**Comment by SimonKnu** [comment]
Hi swistach, do you know when the pro version will be available ? Thanks a lot

**Comment by swistach** [comment]
Hi @SimonKnu, actually today ;)

**Comment by swistach** [comment]
At the very beginning, I would like to say "Thank you!" for @dherges and his project https://github.com/dherges/ng-packagr. Without his work (and community, of course) creating angular wrapper is a nightmare.

So, let's back to the point. We've decided to release one more beta version: 1.0.0-beta4

> Why?

Actually, there are a few things:

1. `handsontable-pro` in `angular` project.
And we did it. You can install `npm i @handsontable-pro/angular handsontable-pro` and everything should works. Of course, currently, there are some limitations. Wrapper works with `@angular/cli 1.5.0+` (Angular 5) and `zone.js 0.8.19+`.
But.
What's about support for Angular 4? (it's an LTS version). We have no answer, yet.
Perhaps, we have to release wrappers separately for Angular 4, Angular 5 and any next version.
My first idea here is to release wrappers as in below example:
`@handonstable/angular@4.0.0` require `@angular/core@^4.0.0`,
`@handonstable/angular@5.0.0` require `@angular/core@^5.0.0`,
`@handonstable/angular@6.0.0` will require `@angular/core@^6.0.0`.

2. Simple installation process.
And this is also done. If you want to use Handsontable in your project you can follow this step by step instruction:
   - install a wrapper and Handsontable
`npm i @handsontable-pro/angular handsontable-pro`
   - import `HotTableModule` to your `app.module.ts`
`import { HotTableModule } from '@handsontable-pro/angular';`
  and add our module to array with rest of imported modules,
   - add `@import '~handsontable-pro/dist/handsontable.full.css';` into your `style.css` file
   - add `<hot-table></hot-table>` into your template.

3. Single npm package for CE and PRO version.
After a few tries to do it, we've decided to release separated wrappers as a scoped packages.
`@handsontable/angular` for Handsontable CE
`@handsontable-pro/angular` for Handsontable PRO
We've figured out a lot of issues with bundling, extra configs for `tsc` and `@angular/cli` and etc.

**Comment by swistach** [comment]
What's next? 
1. We have to find a solution for Angular 4.
2. Publishing process must be automated.
3. We have to update documentation.

**Comment by anandhuajayakumar** [comment]
I tried using the module but it gave me the following error.
`Error: StaticInjectorError(AppModule)[HotTableComponent -> HotTableRegisterer]: 
  StaticInjectorError(Platform: core)[HotTableComponent -> HotTableRegisterer]: 
    NullInjectorError: No provider for HotTableRegisterer!
    at _NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10850)
    at NgModuleRef_.get (core.js:12083)
    at resolveDep (core.js:12573)`

**Comment by swistach** [comment]
Hi @anandhuajayakumar,
could you create a new issue with information about a version of angular and/or angular-cli?

**Comment by anandhuajayakumar** [comment]
@swistach  the error was removed when i added **HotTableRegisterer** as a provider.
I am using angular cli version 1.6.8 and typescript version 2.5.3.
But even though there ain't error the filters are not working.

**Comment by swistach** [comment]
@anandhuajayakumar you can also replace `HotTableModule` with`HotTableModule.forRoot()` in `imports` array in `app.module.ts` file.

If you find new problem, please create new issue (you can do it here: [New issue](https://github.com/handsontable/angular-handsontable/issues/new)
