### ISSUE TITLE
sorting with custom renderer

### ISSUE THREAD

**Issue by brynnlow** [handsontable/angular-handsontable#51]
Hello, its me again 

when i activate columnSorting, the sorting dont move the cell with custom render and let them at their starting point,
it result an incoherence in the data

here is an exemple
https://stackblitz.com/edit/angular-5ykm8c-fb1wmx?file=src%2Fapp%2Fheroes%2Fheroes.component.ts

i have read somewhere to do this for fix: 
`instance.updateSettings({
                        afterColumnSort: () => {
                            i.render();
                            console.log('afterSorting');
                        }
                    }, false);`

but it doesn't work for me

**Comment by swistach** [comment]
Hi @brynnlow,
If you want to get data from getSourceData...(), then you have to be sure, that is logical index.
Here is a demo: https://stackblitz.com/edit/angular-5ykm8c-xb1bsm?file=src/app/heroes/heroes.component.ts

**Comment by brynnlow** [comment]
oh ok i did not know that

thank you for your fast answer
