### ISSUE TITLE
Columns type seems not work

### ISSUE THREAD

**Issue by Iznogood1** [handsontable/angular-handsontable#52]
### Description
Columns type seems not work

### Steps to reproduce
1. Create a table with dynamic columns (https://handsontable.github.io/angular-handsontable/examples/dynamic-columns)
2. Declare the columns in an object  
       columns1: object[] = [ {type : 'numeric'},   {type : 'numeric'}, ...  ];
3. Numeric type seems to be ignored - It partially works when columns are declared in the settings object.

### Demo
https://angular-handsontable-custom-renderer-lecen9.stackblitz.io

Source here :
https://stackblitz.com/edit/angular-handsontable-custom-renderer-lecen9?file=app%2Fapp.component.ts

### Your environment
* Wrapper version: 1.0.0-beta3, released on September 26th, 2017
* Browser : Chrome Version 63.0.3239.108 (Build officiel) (64 bits) / FF 59.0b12 (64 bits)
* Operating System: Win7 64 bits / Win10 64 bits

**Comment by swistach** [comment]
Hi @Iznogood1,
You need to add `type` attribute in `hot-column` element.
Updated example: https://stackblitz.com/edit/angular-handsontable-custom-renderer-s7opf4?file=app%2Fapp.component.html

**Comment by Iznogood1** [comment]
Thanks a lot

**Comment by swistach** [comment]
You're welcome :)
