### ISSUE TITLE
Update of ISSUE_TEMPLATE.md file

### ISSUE THREAD

**Issue by swistach** [handsontable/angular-handsontable#53]
Current `ISSUE_TEMPLATE` file does not contain information about `angular`/`angular-cli version`.
Stackblitz should be added as a default online editor if someone would like to prepare a demo.

**Comment by MateuszG** [comment]
What should the demo contain?
This will be enough https://stackblitz.com/edit/handsontable-angular-remote-data?file=app%2Fapp.component.ts ?
