### ISSUE TITLE
Documentation: Refactor docs code.

### ISSUE THREAD

**Issue by MateuszG** [handsontable/angular-handsontable#59]
### Description
Here is main issue about refactoring code of angular wrapper documentation.

Main things to do:
- [x] Cut navigation menu code from main angular app file.
- [x] Fix "We found a potential security vulnerability in one of your dependencies." #64 

### Steps to reproduce
?

### Demo
None

### Your environment
Irrelevant

**Comment by swistach** [comment]
We will merge wrapper docs into main documentation.
