### ISSUE TITLE
Column reordering not working

### ISSUE THREAD

**Issue by janossuta** [handsontable/angular-handsontable#60]
### Description
When I try to reorder the columns I can't, I added more than 5 column.

### Steps to reproduce

1. set manualColumnMove = true
2. add more than 5 columns
3. try to move the first column to the end
4. try to move the last column to the front

### Demo
https://stackblitz.com/edit/handsontable-angular-access-to-handsontable-qyy9x6

### Your environment
you can see it in the demo

**Comment by MateuszG** [comment]
There is a bug in handsontable library, this should work without any workaround.

For now you can use  `dataSchema` as solution for columns reordering problems (https://docs.handsontable.com/0.37.0/Options.html#dataSchema).

Add this line to settings object:
`dataSchema: {0: null, 1: null, 2: null, 3: null, 4: null, 5: null, 6: null, 7: null},`

Demo
https://stackblitz.com/edit/handsontable-angular-access-to-handsontable-zmd6vk?file=app/app.component.ts

**Comment by janossuta** [comment]
Thank you that's solved my problem!
