### ISSUE TITLE
Is there a way to get the cell data when I use the handsontable column type?

### ISSUE THREAD

**Issue by janossuta** [handsontable/angular-handsontable#61]
### Description
Hi,
Is there a way to get the cell data when I use the handsontable column type?

What I want is to get the ID property of the selected hot-in-hot row and not just a displayed Name property that I set to show in the column.

### Demo
https://stackblitz.com/edit/handsontable-angular-access-to-handsontable-w11jki

**Comment by AMBudnik** [comment]
Hi @janossuta 

here is an example of how to get the data http://jsfiddle.net/gf1tm5bo/ and the property of selected cell from the Handsontable cell type http://jsfiddle.net/b9zxcjat/

**Comment by janossuta** [comment]
Hi @AMBudnik,
 
First of all thank you for your answer, but I still have a question. In this way I have the changed value but how can i get the row id of the parent handsontable and how can I store the changed cell id (maybe in the cellMeta or in an array) especially when I modify more then one row?

**Comment by AMBudnik** [comment]
You can use the `getSelectedLast` method to get the row index - here is the code http://jsfiddle.net/58ccbw4j/

> I modify more then one row

Can you give an example? Do you mean a couple of users changing the data at the same time?

**Comment by AMBudnik** [comment]
I think that we can close the issue as there is no reply for 3 weeks. However, @janossuta feel free to open a new topic or answer here if needed.
