### ISSUE TITLE
Pro under MIT license

### ISSUE THREAD

**Issue by varunrramani** [handsontable/angular-handsontable#63]
If I install handsontable-pro/angular which is under MIT license does that mean I'll be able to use the angular wrapper with the pro features of handsontable on a commercial application without purchasing handsontable pro?

**Comment by AMBudnik** [comment]
Hi @varunrramani 

*angular-handsontable* is only a wrapper. If you install *handsontable-pro* within the wrapper you will be able to use PRO but without the `licenseKey `settings it will appear as an evaluation version.
