### ISSUE TITLE
HotTableRegisterer getInstance trouble

### ISSUE THREAD

**Issue by Iznogood1** [handsontable/angular-handsontable#69]
### Description
Trying to use HotTableRegisterer  as in the documentation **Access the Handsontable instance**: https://handsontable.github.io/angular-handsontable/examples/access-to-handsontable

### Demo
https://angular-hot-instance-issue.stackblitz.io

I get 2 errors:
1/ _**hot.selection.empty**_ is not a function (displayed in the console)
2/ If I edit the code, then **_...getInstance(this.instance)_** does not return any object

I have forked the provided example (https://handsontable.github.io/angular-handsontable/examples/access-to-handsontable).
If I edit any file (for instance, just add an empty line in app.component.ts) I get the same behaviour : getInstance does not return any object and the example does not work anymore.

### Your environment
* Wrapper version: 1.0.0.beta4
* Browser Name and version: FF59 / Chrome64
* Operating System: Win7 / Win10

**Comment by MateuszG** [comment]
Everything works for me. The only problem I know about is with stackblitz.io, when you changing the code "instances are lost" and to be able to view app correctly, you need to reload it (button is located in preview section of stackblitz.

**Comment by Iznogood1** [comment]
Thanks Mateus,

I wanted to set some Handsontable instance properties.

In order to have it working I have had to use ViewChild and AfterViewInit.

import { Component,  ViewChild, AfterViewInit, ... } from '@angular/core';

```
export class AppComponent implements OnInit, AfterViewInit  {
 @ViewChild(HotTableRegisterer) hot;

  beforeChange (changes, source) {
    console.log('Before change:');
    console.log('changes ', changes);
    console.log('source ', changes);
    //changes[0] = null;
  }

  ngAfterViewInit() {
    this.hot.getInstance('1').updateSettings({
      beforeChange : this.beforeChange
    });
  }
...
}
```

**Comment by Mathijs003** [comment]
I have this problem too. 

@ViewChild does not work for me. 

ts:


```
export class PreviewComponent implements OnInit {

  public previewData: any;
  public previewHTableId : any;
  public previewHTable: Handsontable;
  

  constructor(private hotRegisterer: HotTableRegisterer) { }

  ngOnInit() {
    this.previewData = Handsontable.helper.createEmptySpreadsheetData(30, 1);
  }

  testHot(){
    const previewHTable = this.hotRegisterer.getInstance(this.previewHTableId);
    console.log(previewHTable) // --> undefined
  }
}
```


html: 


```
<hot-table
      [colHeaders]="true"
      [rowHeaders]="true"
      [height]="300"
      [stretchH]="'all'"
      [data]="previewData"
      [hotId]="previewHTableId"
    ></hot-table>
```

**Comment by swistach** [comment]
Hi @Mathijs003, `previewHTableId` should be a string.  In your example is `undefined`.
Try to replace `public previewHTableId : any;` with `public previewHTableId = 'hot';`

**Comment by Mathijs003** [comment]
@swistach Great, thanks you very much!
