### ISSUE TITLE
Add angular-handsontable API documentation to gh-pages

### ISSUE THREAD

**Issue by madoar** [handsontable/angular-handsontable#7]
Currently the `gh-pages` only contain a link to the API documentation of `handsontable` itself. What's missing is a documentation of the angular components, i.e. `hot-column`, `hot-table`, and so on.

I know of two tools to automatically create typescript documentations, maybe they are of some use to you:
- https://github.com/TypeStrong/typedoc
- https://github.com/compodoc/compodoc

**Comment by swistach** [comment]
Good idea, but first, we have to improve typings (as I wrote in #12).

**Comment by swistach** [comment]
Wrapper API should be available in new version of our main documentation.
