### ISSUE TITLE
Numeric format ignored on release 1.0.0-beta4

### ISSUE THREAD

**Issue by Iznogood1** [handsontable/angular-handsontable#72]
### Description
I am trying to apply a numeric format to some columns
But it seems not to work

### Steps to reproduce
The settings
```
settings = {
    data : [[1 ,2], [5, 6]],
    columns: [
      {type : 'numeric', format: '$0,0.00'}, 
      {type : 'numeric', format: '$0,0.00'}
      ]
   }
```
The component
`<hot-table [settings]="settings" ></hot-table>`

### Demo
https://stackblitz.com/edit/angular-handsontable-numericformat-issue

### Your environment
* Wrapper version: 1.0.0-beta4
* Browser Name and version: FF60 / Chrome65
* Operating System: Win10 / Win7

**Comment by AMBudnik** [comment]
Hi @Iznogood1 

we've changed the syntax for numeric cell type format (Handsontable CE related).

Here's an updated example https://stackblitz.com/edit/angular-handsontable-numericformat-issue-zkbytk?file=app/app.component.ts
