### ISSUE TITLE
Uncaught (in promise): TypeError: Cannot read property 'call' of undefined TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by VinceZK** [handsontable/angular-handsontable#73]
### Description

Handsontable page display empty with production compilation using Angular CLI 1.6 and Angular5.  The Chrome console says: 

> "main.945b4e943534575f178b.bundle.js:1
> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined ..."

Angular development mode works OK.

### Steps to reproduce
1. Follow your standard steps in (https://handsontable.github.io/angular-handsontable/quick-start). 
2. run a production build: `ng build --prod --build-optimizer`
3. Expose the `dist` folder in Express web server

### Demo
Test the error in:  http://darkhouse.com.cn/portal/handsontable/handsontable

Related codes can be found in git repo: https://github.com/VinceZK/Portal/tree/master/src/app, in the folder *handsontable*

### Your environment
* Wrapper version: "@handsontable/angular": "^1.0.0-beta4", "handsontable": "^0.38.1",
* Browser Name and version: Version 65.0.3325.181
* Operating System: MACOS
* Angular:  "@angular/cli": "1.6.4", Angular 5.1

**Comment by swistach** [comment]
Hi @VinceZK,
Unfortunately, there is a problem with integration between `--prod`, lazy loading in `@angular/router` and Handsontable library. A chunk with the `HandsontableModule` is broken but I think it is an issue with the library, not a wrapper.

**Comment by VinceZK** [comment]
Hello swistach,
May I ask when the bug will be fixed?

**Comment by VinceZK** [comment]
The issue is resolved after upgraded to Angular 6
