### ISSUE TITLE
Date doesn't get formatted at cells with type 'date'

### ISSUE THREAD

**Issue by nmingaleev** [handsontable/angular-handsontable#74]
### Description

I am trying to format date as follows 
![image](https://user-images.githubusercontent.com/16058740/38309334-0064b552-3844-11e8-8358-3febfd030ac7.png)
but getting:
![image](https://user-images.githubusercontent.com/16058740/38309363-172451e4-3844-11e8-971a-fd61ad4f5dd8.png)
I tried to validate cells after the table gets initialized, but it didn't help.
![image](https://user-images.githubusercontent.com/16058740/38309448-507e7550-3844-11e8-9152-ccfbe11f473b.png)

If I format date before passing it to the table, it will display as expected
![image](https://user-images.githubusercontent.com/16058740/38309547-8af2ed1a-3844-11e8-8c1b-0e2e8b4170dc.png)
![image](https://user-images.githubusercontent.com/16058740/38309565-9593620e-3844-11e8-89b0-c293e12e2c9b.png)

But in that case sorting won't work as expected
![image](https://user-images.githubusercontent.com/16058740/38309731-ec3687f8-3844-11e8-95bc-9ccfeec8fbb2.png)

### Your environment
* Wrapper version: ^1.0.0-beta3
* Browser Name and version: Google Chrome 64
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @nmingaleev 

Which version of Handsontable are you loading? It sounds more like the Handsontable fault rather than something with the wrapper. but I might be wrong.

**Comment by nmingaleev** [comment]
handsontable@0.34.4, I think I can make a demo during the next two days

**Comment by nmingaleev** [comment]
@AMBudnik , handsontable@0.34.4. I think I can make a demo during the next two days

**Comment by AMBudnik** [comment]
OK, great. I think that the issue was previously seen it Handsontable (vanilla) but got solved over time. Maybe this one https://github.com/handsontable/handsontable/issues/3588 < but this should be working since `0.29.0` (CE)

**Comment by swistach** [comment]
Hi @nmingaleev,
I've prepared simple example in vanilla js: https://jsfiddle.net/tgLkwh2a/
Formatting and sorting work as we expected.
Could you reopen this issue when you prepare a demo?
