### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module 

### ISSUE THREAD

**Issue by tavai89** [handsontable/angular-handsontable#75]
### Description
I getting following error when trying to build my angular 4 application

ERROR in Error: Metadata version mismatch for module /node_modules/@handsontable/angular/handsontable-angular.d.ts, found version 4, expected 3

Versions:

"@handsontable/angular": "^1.0.0-beta4",
"handsontable": "^2.0.0",

### Your environment
* Wrapper version: ^1.0.0-beta4
* Browser Name and version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System: Win 10

**Comment by AMBudnik** [comment]
Thanks for reporting. We'll check that.

**Comment by tavai89** [comment]
Thank you

**Comment by swistach** [comment]
Hi @tavai89,
`@handsontable/angular@1.0.0-beta4` is not compatible with `@angular/core@^4.0.0`.
If you want to use this version of the wrapper, then you have to upgrade `@angular/core` version to `^5.0.0`

**Comment by tavai89** [comment]
Hi @swistach. Thank you for answering. But what would your recommendation if I need to use angular 4 version (by the customer requirements)?

**Comment by swistach** [comment]
If you want to use Handsontable CE then you can downgrade wrapper to `angular-handsontable@1.0.0-beta3`.

If you want to use Handsontable PRO and then you can copy `lib/pro/src` directory into your project.
Sorry for this inconvenience.

**Comment by swistach** [comment]
@jackxxu if you would like to use wrapper + Angular 4 then you should use the previous package version, look at https://www.npmjs.com/package/angular-handsontable

**Comment by vaidyasaurabh08** [comment]
Hi guys,
So, @swistach @jackxxu 
Even I have the same requirement of using Angular 4 and handsontable.

If I am getting it correct, I should 
"npm i handsontable@1.0.0-beta4" ??
Is this correct?

**Comment by abhishek3999** [comment]
you can use npm i angular-handsontable@^1.0.0-beta4.
It's suitable for angular 4

**Comment by vaidyasaurabh08** [comment]
Yeah, tried that , it works. But its deprecated. Guess ill upgrade angular.
