### ISSUE TITLE
Support for option selectionMode

### ISSUE THREAD

**Issue by stephenheard** [handsontable/angular-handsontable#76]
### Description
Please add support for option selectionMode
https://docs.handsontable.com/2.0.0/Options.html#selectionMode

"selectionMode: single" was previously "multiSelect: true", changed in v 0.36.0

**Comment by stephenheard** [comment]
Created PR https://github.com/handsontable/angular-handsontable/pull/77

**Comment by stephenheard** [comment]
Done!

**Comment by AMBudnik** [comment]
Thanks :)

**Comment by swistach** [comment]
Hi @stephenheard, could you look into #77. I sent you a few remarks to do, before we will be able to merge your changes.

**Comment by stephenheard** [comment]
Will do - it is on my To Do list.  Thanks!

**Comment by swistach** [comment]
Hi @stephenheard,
Thank you for your PR, `@Input() selectionMode` is now available in a component. (check `@handsontable/angular@2.0.0`)
