### ISSUE TITLE
instance of handsontable can't run a hook

### ISSUE THREAD

**Issue by Mathijs003** [handsontable/angular-handsontable#78]
### Description
The instance of the HOT retrieved by a HotTableRegisterer should be able to run a hook. 

### Steps to reproduce
let HTableInstance = this.hotRegisterer.getInstance(this.datagridHTableId);
HTableInstance.run('afterChange'); // ---> not working

the runHooks() function is available but isn't doing anything

### Your environment
* Wrapper version: @handsontable/angular@1.0.0-beta4
* Browser Name and version: Chrome
* Operating System: Mac OS

**Comment by swistach** [comment]
Hi @Mathijs003,
I've prepared an example with runHooks: https://stackblitz.com/edit/angular-handsontable-ce-ezbcvw?file=app%2Fapp.component.ts maybe it could be helpful for you.
If not, please prepare a demo on stackblitz with a short explanation what you would like to achieve :)
