### ISSUE TITLE
Problem when scrolling in angular-handsontable demo

### ISSUE THREAD

**Issue by madoar** [handsontable/angular-handsontable#8]
When scrolling the demo at https://handsontable.github.io/angular-handsontable/examples/settings-object the scrolling seems to be bugged:
![peek 2017-09-07 11-41](https://user-images.githubusercontent.com/18488086/30157133-bc410b7c-93c1-11e7-9c37-74ec14f25e73.gif)

I'm using Linux Mint 18.2 with Firefox 55.0.2

**Comment by swistach** [comment]
Thank you @madoar. Now should be ok.

**Comment by madoar** [comment]
Yes, it's fixed now :)
