### ISSUE TITLE
angular-handsontable includes moment in bundle

### ISSUE THREAD

**Issue by ipassynk** [handsontable/angular-handsontable#82]
### Description
angular-handsontable includes moment in the bundle

### Steps to reproduce
Our application already includes moment library and angular-handsontable includes another copy of moment.

### Demo
https://github.com/ipassynk/handsontable-size.git
Run
```
yarn build
yarn bundle-report
```

See that moment is included twice.

### Your environment
* Wrapper version:
* Browser Name and version:
* Operating System:

**Comment by swistach** [comment]
Hi @ipassynk,
this is a result of the fixed version in `package.json` file of Handsontable.
We will talk about it inside our core team.
Moreover, you can follow this PR: handsontable/handsontable#5047
