### ISSUE TITLE
Cannot cancel paste event

### ISSUE THREAD

**Issue by smart-guid** [handsontable/angular-handsontable#83]
### Description

Documentation states during beforePaste event, the paste can be cancelled.  This functionality does not function according to the documentation.

See demo I have created,

https://stackblitz.com/edit/angular-handsontable-ce-hx3axx?embed=1&file=app/app.component.ts

**Comment by swistach** [comment]
Hi @smart-guid,
unfortunately, currently, you can cancel pasting only if you define `beforePaste` inside a settings object. https://stackblitz.com/edit/angular-handsontable-ce-pxxp9b?file=app%2Fapp.component.ts

**Comment by smart-guid** [comment]
This is undocumented behavior.  This event as well as all other events should function the same no matter how the events are wired up.

This is still considered a bug.

**Comment by swistach** [comment]
You're right, we should mention about this in our documentation :+1:

Actually, event emitting in @Output is not the same thing as function or arrow function defined in a settings object.

@Output uses EventEmitter to emit custom component events. You can listen on occurring of this event.
But, EventEmitter extends `rxjs/Subject`. So I dive into the code and `EventEmitter.emit()` calls `super.next()`, but `Subject.next()` can returns only `undefined`. That means you cannot return values inside the EventEmitter callback.
Source code:
https://github.com/angular/angular/blob/5.2.10/packages/core/src/event_emitter.ts#L79
http://reactivex.io/rxjs/file/es6/Subject.js.html#lineNumber36

You can find a similar question here: https://stackoverflow.com/questions/38102948/how-to-return-a-value-from-an-eventemitter-function

**Comment by swistach** [comment]
The question is, did we used @Outputs correctly? Maybe these hooks should be only as @Inputs. What do you think?

**Comment by swistach** [comment]
Hi @smart-guid,
I've just released new version. Now you can use hooks as @Input:
```html
<hot-table [beforePaste]="onBeforePaste"></hot-table>
```
```ts
onBeforePaste = (hotInstance, data, coords) => {
  return false;
}
```
