### ISSUE TITLE
Move the div creation to the hot-table template

### ISSUE THREAD

**Issue by madoar** [handsontable/angular-handsontable#85]
I think it would be easier readable and more in line with angular, if the `div` creation was moved from the `ngOnInit` method to the `template` of the component.

In theory this should be quite easy.
It should simply require the addition of a `div` element to the template with an id.
This id could then be used to inject the div element with the id into the hot-table component via the `@ViewChild` decorator.
Afterwards the div element should be available inside the `ngAfterViewInit` callback method of the hot-table component.

**Comment by swistach** [comment]
Released in 3.0.0
