### ISSUE TITLE
Create common super types for all classes contained in both the ce and pro folders

### ISSUE THREAD

**Issue by madoar** [handsontable/angular-handsontable#86]
Currently the classes with the same name in both the ce and pro folders have a lot of code, that is redundant, i.e. contained in both classes.

This redundancy has multiple disadvantages:
- it makes implementing new features and improving old features harder, because all changes need to be made in both folders
- it makes it possible to have bugs in only one of the folders through for example spelling errors
- it makes it hard to see where the difference between both versions are located

To solve these disadvantages I suggest to add a common super class for each two classes with the same name in both the ce and pro folders, i.e. for the following components/directives/services:
- `hot-column`
- `hot-table`
- `hot-table-registerer`
- `hot-settings-resolver`

These common super classes should contain all fields and methods, which are contained in both the ce and pro folders.
Afterwards the classes inside the ce and pro folders should extend the common super class and only contain the fields that differ from it.

**Comment by swistach** [comment]
Hi @madoar,
you are right, both of lib/src directories are almost the same.
When I worked on v1.0.0-beta4, I found a few problems with bundling with the similar schema.
I will back to this issue after v1.0.0-beta6 release.
I think, now, we have a good start point to improve our wrapper.
Thank you for your contribution!

**Comment by swistach** [comment]
We merge components CE and PRO in #142. Thank you for your suggestion and don't forget to look at `@handsontable/angular@4.0.0` after release 😃
