### ISSUE TITLE
Optimize bundle size

### ISSUE THREAD

**Issue by Frennetix** [handsontable/angular-handsontable#89]
### Description

I imported angular-handsontable in my project and after running some test I was surprise that the lib itself took more than a third of my application.

### Steps to reproduce

    npm install --save-dev webpack-bundle-analyzer

    "bundle-report": "ng build --prod --stats-json && webpack-bundle-analyzer dist/stats.json",

Without the lib (1.25MB - 60.39Kb gzip)
![handsomeempty](https://user-images.githubusercontent.com/12666188/39946366-299b5de4-556e-11e8-9aeb-102387aea612.png)

With the lib (3.54MB - 279.38 KB gzip)
![handsomefull](https://user-images.githubusercontent.com/12666188/39946367-2b9094de-556e-11e8-85eb-7e55b956f1f4.png)

Is all moment local need to be be included ? (23.80% of the bundle size)

Same for numbro langage? (1.34% of the bundle size)

Also according to these reports both import the full version of the lib instead of the min one.

> node_modules/handsontable-pro/dist/handsontable.js
> node_modules/handsontable/dist/handsontable.js

### Demo

https://stackblitz.com/edit/handsontable-angular

### Your environment

```
Angular CLI: 6.0.1
Node: 9.11.1
OS: win32 x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.13
@angular-devkit/build-angular     0.5.13
@angular-devkit/build-optimizer   0.5.13
@angular-devkit/core              0.5.13
@angular-devkit/schematics        0.6.1
@ngtools/webpack                  6.0.0-rc.11
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by swistach** [comment]
Hi @Frennetix,
Thank you for investigation. Indeed, `momentjs` has a problem with bundling.
I found similar issues on moment issue-board:
https://github.com/moment/moment/issues/4504
https://github.com/moment/moment/issues/4025
https://github.com/moment/moment/issues/2517
We will verify our implementation, but it looks like a bug in `momentjs`.

**Comment by swistach** [comment]
Hi @Frennetix,
Unfortunately, `momentjs` still didn't fix the loading process for locales in their library.

However, you can check this article: https://codeburst.io/customizing-angular-cli-6-build-an-alternative-to-ng-eject-a48304cd3b21
Maybe it will help you to find a way to modify a webpack configuration to exclude momentjs' locales from a build.

Thank you for your help and detailed investigation!
