### ISSUE TITLE
example for angular access not working

### ISSUE THREAD

**Issue by mtoback** [handsontable/angular-handsontable#90]
### Description
Expect example to create a spreadsheet, allow you to edit it then clear selected cells

### Steps to reproduce

1. Go to :https://handsontable.github.io/angular-handsontable/examples/access-to-handsontable
2. Note that selection in app.component.ts is in red (not supported)
3. Go to the result and click on it to start
4. Result: spreadsheet comes up but is not clear

### Demo

https://stackblitz.com/edit/handsontable-angular-access-to-handsontable?file=app%2Fapp.component.ts

Note that when you go to the stackblitz, you can set an alert and see that the instance is undefined in the clearSelection() method
### Your environment
* Angular version:  Running this using the example provided
* Handsontable version: 1.0.0.beta4
* Wrapper version:
* Browser Name and version: Version 66.0.3359.139 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by swistach** [comment]
Hi @mtoback,
Thank you for sharing. I fixed an example.
