### ISSUE TITLE
Handsontable v3

### ISSUE THREAD

**Issue by metaloha** [handsontable/angular-handsontable#91]
Does the wrapper work with the new release of Handsontable? The sorting API appears to have changed, not sure if that's a concern for the wrapper or not.

**Comment by AMBudnik** [comment]
Hi @metaloha 

that is correct, in `3.0.0.` of Handsontable we've added some backward-incompatible sorting changes. Here are the release notes https://docs.handsontable.com/pro/3.0.0/tutorial-release-notes.html

**Comment by AMBudnik** [comment]
The wrapper should already work fine with Handsontable PRO `3.0.0`. You just need to change the API or settings that you've used before and now are changed.

**Comment by Calidus** [comment]
The documentation says run:
`npm install @handsontable/angular handsontable` which now pulls 3.0 but @handsontable/angular has a dependency of .35.1

**Comment by 10jayshah** [comment]
the npm version of this module hasnt been update past beta3... is this going to be updated to the latest any time soon?

**Comment by swistach** [comment]
Hi @Calidus, `handsontable` package is now a peerDependency. That means you decide which version you would like to use. We suggest `0.35.1`, but it should work with 2.0, 3.0 and even with some previous version eg.: 0.30.0.

@10jayshah we will release next version very soon.

**Comment by swistach** [comment]
`peerDependency` will be bumped in #83.
