### ISSUE TITLE
$event.hotInstance is undefined in afterInit hook

### ISSUE THREAD

**Issue by denaje** [handsontable/angular-handsontable#93]
### Description

I would expect to be able to access the Handsontable instance from `$event` in the `afterInit` hook, but `$event.hotInstance` is undefined.

### Steps to reproduce

1. Register `afterInit` hook, passing in `$event`.
2. See that `$event.hotInstance` is undefined.

### Demo

https://stackblitz.com/edit/handsontable-angular-hooks-7d5c8a

### Your environment

* Angular version: 5.2.9
* Handsontable version: 3.0.0
* Wrapper version: 1.0.0-beta5
* Browser Name and version: Google Chrome 67.0.3396.62
* Operating System: Linux

### Other Notes

It does not seem possible to use `HotTableRegisterer` to get access to the Handsontable instance because the instance is not registered until after the `afterInit` hook has fired. Is there an alternate way I can gain access to the instance?

**Comment by swistach** [comment]
Hi @denaje,
thank you for your sharing. You're right. The instance is not registered in HotTableRegisterer.
I think it's a similar thing as I mentioned in #83 ([comment](https://github.com/handsontable/angular-handsontable/issues/83#issuecomment-386064735)).

**Comment by denaje** [comment]
@swistach To be clear, are you saying that this issue will be fixed when #83 is fixed?

**Comment by swistach** [comment]
@denaje exactly :)
