### ISSUE TITLE
Contextmenu disable selection (deletion) of multiple rows at once

### ISSUE THREAD

**Issue by Mathijs003** [handsontable/angular-handsontable#95]
### Description
Is there a way to prevent the user from deleting multiple rows/columns at once using the contextmenu?

**Comment by AMBudnik** [comment]
Hi @Mathijs003 
there's a hook called [`beforeRemoveRow`](https://docs.handsontable.com/pro/1.16.0/Hooks.html#event:beforeRemoveRow).  You can use the 2nd parameter `amount` to block ( `return false`) for `amount > 1`.
Here's a demo http://jsfiddle.net/0zg8hpqj/

**Comment by Mathijs003** [comment]
Hi @AMBudnik, thanks for your reply. I'm using the beforeRemoveRow and returning a false in the event function but it won't work. (see [#96](https://github.com/handsontable/angular-handsontable/issues/96))

**Comment by AMBudnik** [comment]
you should refer to a second parameter of the `beforeRemoveRow` hook that stands for the `amount` of rows that will be deleted if you'd like to disallow to remove more than one row.
Here is an example with Angular https://stackblitz.com/edit/angular-5ykm8c-svrj5b?file=src/app/heroes/heroes.component.ts

**Comment by Mathijs003** [comment]
@AMBudnik thanks, this works. But only if the function is added trough the settings object. If you add it on the (beforeRemoveRow) hook in the html, it won't work.

But thanks, this will do the trick!
