### ISSUE TITLE
Read only first row in settings is not updated when adding row on top

### ISSUE THREAD

**Issue by Mathijs003** [handsontable/angular-handsontable#97]
### Description
If you want to disable a row in an HOTable you can do it in the settings like so : 

```
        cells: (row, col, prop) => {
          const cellProperties: any = {};
            if (row === 0) {
              cellProperties.readOnly = true;
            }
          return cellProperties;
        }
```

If you then **add a row above**, the read only status stayed on the row that is now not the first row anymore. 

**This behaviour works in plain javascript, but not in the angular wrapper.** (see demo)

### Demo

Angular example with issue: 
[https://stackblitz.com/edit/handsontable-angular-hooks-wunmdb](https://stackblitz.com/edit/handsontable-angular-hooks-wunmdb)

Javascript example without the issue:
[http://jsfiddle.net/75z1b38s/](http://jsfiddle.net/75z1b38s/)

### Your environment
* Angular version: 5.2.0
* Handsontable version: 2.0.0
* Wrapper version: 1.0.0-beta5
* Browser Name: Chrome
* Operating System: OSx

**Comment by AMBudnik** [comment]
They work the same way on Windows (win 10/Chrome 66). Maybe there's something with the Mac. Thanks! We'll check that.

**Comment by AMBudnik** [comment]
I just got the same result on Mac. Both examples maintain the read-only state for the row where they have been set and for a new row when added to a position with an index of `0`.
Do you want the newly added row to be read-only and erase the state for the old row?

**Comment by Mathijs003** [comment]
Yes, strange, this happened yesterday, but not now. How can I erase the state of the old row?

**Comment by AMBudnik** [comment]
To erase it you need to add ELSE 

```
cells: (row, col, prop) => {
          const cellProperties: any = {};
            if (row === 0) {
              cellProperties.readOnly = true;
            } else { cellProperties.readOnly = false; }
          return cellProperties;
        }
```

**Comment by Mathijs003** [comment]
Great, thanks @AMBudnik

**Comment by AMBudnik** [comment]
you're welcome @Mathijs003
