### ISSUE TITLE
Date format with object date

### ISSUE THREAD

**Issue by brynnlow** [handsontable/angular-handsontable#98]
Hello,

i have a problem with the date, when I hydrate my table with a dateObject it dont give me the correct format

i receive it: Wed Jun 06 2018 16:48:58 GMT+0200 (CEST)
when i ask for: { data: 'birthday', type: 'date', dateFormat: 'YYYY-MM-DD', correctFormat: true}

exemple here : https://stackblitz.com/edit/angular-5ykm8c-hcrizl?file=src%2Fapp%2Fheroes%2Fheroes.component.ts

what can i do ? i have to do it with a string or something else ?

**Comment by AMBudnik** [comment]
` dateFormat: 'YYYY-MM-DD',` is used to format string type data `10/10/2010` or `10-10-2010` will become `2010-10-10` but we do not fully support `Date()` method

**Comment by swistach** [comment]
Hi @brynnlow,
you can subscribe handsontable/handsontable#4291 to be up to date with the information related to this issue.
