### ISSUE TITLE
Fail to use validateRows method with HotTableRegisterer service

### ISSUE THREAD

**Issue by kyleleow** [handsontable/angular-handsontable#99]
### Description
Fail to use `validateRows` method.

### Steps to reproduce

1. Add a `HotTableRegisterer` service to register handsontable instance:
`const hotInstance = this.hotRegisterer.getInstance(this.instance);`
2. Try to use method as such:
`hotInstance.validateRows([0], (valid) => {alert(valid)});`
3. Code fails to compile saying validateRows is not a valid function.
4. I am referring to the 0.35.0 CE doc [here](https://docs.handsontable.com/0.35.0/Core.html#validateRows).

### Your environment
* Angular version: 5.0.0
* Handsontable version: 0.35.0
* Wrapper version: 1.0.0 beta 3
* Browser Name and version: Chrome 67
* Operating System: Win 10 1803

**Comment by swistach** [comment]
Hi @kyleleow,
Thank you for your sharing. Unfortunately, `validateRows` and `validateColumns` are not defined in our [definition file](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts).

**Comment by swistach** [comment]
I close this issue 'cause we will add `validateRows` and `validateColumns` to our definition file soon.

Thank you again @kyleleow! 👍
